/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.apis.AstronautsApi
import me.calebjones.spacelaunchnow.api.trantor.models.AstronautDetail
import me.calebjones.spacelaunchnow.api.trantor.models.HTTPValidationError
import me.calebjones.spacelaunchnow.api.trantor.models.PaginatedResponseAstronautList

class AstronautsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AstronautsApi
        //val apiInstance = AstronautsApi()

        // to test getAstronautApiV1AstronautsAstronautIdGet
        should("test getAstronautApiV1AstronautsAstronautIdGet") {
            // uncomment below to test getAstronautApiV1AstronautsAstronautIdGet
            //val astronautId : kotlin.Int = 56 // kotlin.Int | 
            //val result : AstronautDetail = apiInstance.getAstronautApiV1AstronautsAstronautIdGet(astronautId)
            //result shouldBe ("TODO")
        }

        // to test listAstronautsApiV1AstronautsGet
        should("test listAstronautsApiV1AstronautsGet") {
            // uncomment below to test listAstronautsApiV1AstronautsGet
            //val statusIds : kotlin.String = statusIds_example // kotlin.String | Comma-separated astronaut status ids
            //val agencyIds : kotlin.String = agencyIds_example // kotlin.String | Comma-separated agency ids
            //val hasFlown : kotlin.Boolean = true // kotlin.Boolean | true â†’ flights_count > 0; false â†’ 0 or unrecorded
            //val inSpace : kotlin.Boolean = true // kotlin.Boolean | Currently in space
            //val isHuman : kotlin.Boolean = true // kotlin.Boolean | true â†’ excludes astronaut type 'Non-Human'; false â†’ only that type. An astronaut with no recorded type counts as human.
            //val search : kotlin.String = search_example // kotlin.String | Search astronaut name
            //val ordering : kotlin.String = ordering_example // kotlin.String | Order by `name`. Prefix - for descending. Unknown values fall back to name.
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results per page
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of results to skip
            //val result : PaginatedResponseAstronautList = apiInstance.listAstronautsApiV1AstronautsGet(statusIds, agencyIds, hasFlown, inSpace, isHuman, search, ordering, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
