/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.apis.EventsApi
import me.calebjones.spacelaunchnow.api.trantor.models.EventDetail
import me.calebjones.spacelaunchnow.api.trantor.models.HTTPValidationError
import me.calebjones.spacelaunchnow.api.trantor.models.PaginatedResponseEventList

class EventsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EventsApi
        //val apiInstance = EventsApi()

        // to test getEventApiV1EventsEventIdGet
        should("test getEventApiV1EventsEventIdGet") {
            // uncomment below to test getEventApiV1EventsEventIdGet
            //val eventId : kotlin.Int = 56 // kotlin.Int | 
            //val result : EventDetail = apiInstance.getEventApiV1EventsEventIdGet(eventId)
            //result shouldBe ("TODO")
        }

        // to test listEventsApiV1EventsGet
        should("test listEventsApiV1EventsGet") {
            // uncomment below to test listEventsApiV1EventsGet
            //val upcoming : kotlin.Boolean = true // kotlin.Boolean | true â†’ date now or later; false â†’ date in the past. Pure filter â€” combine with ordering=date for soonest-first.
            //val dateAfter : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | Date at or after this datetime (ISO 8601)
            //val dateBefore : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | Date at or before this datetime (ISO 8601)
            //val typeIds : kotlin.String = typeIds_example // kotlin.String | Comma-separated event type ids
            //val programIds : kotlin.String = programIds_example // kotlin.String | Comma-separated program ids
            //val launchId : kotlin.String = launchId_example // kotlin.String | Launch id â€” related events for a launch
            //val search : kotlin.String = search_example // kotlin.String | Search event name
            //val ordering : kotlin.String = ordering_example // kotlin.String | Order by `date`. Prefix - for descending. Unknown values fall back to -date.
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results per page
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of results to skip
            //val result : PaginatedResponseEventList = apiInstance.listEventsApiV1EventsGet(upcoming, dateAfter, dateBefore, typeIds, programIds, launchId, search, ordering, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
