/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.apis.LauncherConfigurationsApi
import me.calebjones.spacelaunchnow.api.trantor.models.HTTPValidationError
import me.calebjones.spacelaunchnow.api.trantor.models.LauncherConfigFull
import me.calebjones.spacelaunchnow.api.trantor.models.PaginatedResponseLauncherConfigSummary

class LauncherConfigurationsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LauncherConfigurationsApi
        //val apiInstance = LauncherConfigurationsApi()

        // to test getConfigurationApiV1ConfigurationsConfigIdGet
        should("test getConfigurationApiV1ConfigurationsConfigIdGet") {
            // uncomment below to test getConfigurationApiV1ConfigurationsConfigIdGet
            //val configId : kotlin.Int = 56 // kotlin.Int | 
            //val expand : kotlin.String = expand_example // kotlin.String | Comma-separated list of relations to expand. Dot notation for nested: provider,rocket.stages.launcher
            //val result : LauncherConfigFull = apiInstance.getConfigurationApiV1ConfigurationsConfigIdGet(configId, expand)
            //result shouldBe ("TODO")
        }

        // to test listConfigurationsApiV1ConfigurationsGet
        should("test listConfigurationsApiV1ConfigurationsGet") {
            // uncomment below to test listConfigurationsApiV1ConfigurationsGet
            //val search : kotlin.String = search_example // kotlin.String | Search by name
            //val active : kotlin.Boolean = true // kotlin.Boolean | Filter by active status
            //val manufacturerId : kotlin.Int = 56 // kotlin.Int | Filter by manufacturer agency ID
            //val reusable : kotlin.Boolean = true // kotlin.Boolean | Filter by reusable status
            //val familyIds : kotlin.String = familyIds_example // kotlin.String | Comma-separated rocket family ids
            //val programIds : kotlin.String = programIds_example // kotlin.String | Comma-separated program ids
            //val isPlaceholder : kotlin.Boolean = true // kotlin.Boolean | Filter by placeholder status
            //val ordering : kotlin.String = ordering_example // kotlin.String | Order by `name`, `maiden_flight`, or `total_launch_count`. Prefix - for descending. Unknown values fall back to name.
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results per page
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of results to skip
            //val result : PaginatedResponseLauncherConfigSummary = apiInstance.listConfigurationsApiV1ConfigurationsGet(search, active, manufacturerId, reusable, familyIds, programIds, isPlaceholder, ordering, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
