/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.apis.PadsApi
import me.calebjones.spacelaunchnow.api.trantor.models.HTTPValidationError
import me.calebjones.spacelaunchnow.api.trantor.models.PadFull
import me.calebjones.spacelaunchnow.api.trantor.models.PaginatedResponsePadSummary

class PadsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PadsApi
        //val apiInstance = PadsApi()

        // to test getPadApiV1PadsPadIdGet
        should("test getPadApiV1PadsPadIdGet") {
            // uncomment below to test getPadApiV1PadsPadIdGet
            //val padId : kotlin.Int = 56 // kotlin.Int | 
            //val expand : kotlin.String = expand_example // kotlin.String | Comma-separated list of relations to expand. Dot notation for nested: provider,rocket.stages.launcher
            //val result : PadFull = apiInstance.getPadApiV1PadsPadIdGet(padId, expand)
            //result shouldBe ("TODO")
        }

        // to test listPadsApiV1PadsGet
        should("test listPadsApiV1PadsGet") {
            // uncomment below to test listPadsApiV1PadsGet
            //val search : kotlin.String = search_example // kotlin.String | Search pad name
            //val locationId : kotlin.Int = 56 // kotlin.Int | Filter by location ID
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results per page
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of results to skip
            //val result : PaginatedResponsePadSummary = apiInstance.listPadsApiV1PadsGet(search, locationId, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
