/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.apis.ProgramsApi
import me.calebjones.spacelaunchnow.api.trantor.models.HTTPValidationError
import me.calebjones.spacelaunchnow.api.trantor.models.PaginatedResponseProgramList
import me.calebjones.spacelaunchnow.api.trantor.models.ProgramDetail

class ProgramsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProgramsApi
        //val apiInstance = ProgramsApi()

        // to test getProgramApiV1ProgramsProgramIdGet
        should("test getProgramApiV1ProgramsProgramIdGet") {
            // uncomment below to test getProgramApiV1ProgramsProgramIdGet
            //val programId : kotlin.Int = 56 // kotlin.Int | 
            //val result : ProgramDetail = apiInstance.getProgramApiV1ProgramsProgramIdGet(programId)
            //result shouldBe ("TODO")
        }

        // to test listProgramsApiV1ProgramsGet
        should("test listProgramsApiV1ProgramsGet") {
            // uncomment below to test listProgramsApiV1ProgramsGet
            //val search : kotlin.String = search_example // kotlin.String | Search program name
            //val ordering : kotlin.String = ordering_example // kotlin.String | Order by `name`. Prefix - for descending. Unknown values fall back to name.
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results per page
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of results to skip
            //val result : PaginatedResponseProgramList = apiInstance.listProgramsApiV1ProgramsGet(search, ordering, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
