/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.apis.SpacecraftApi
import me.calebjones.spacelaunchnow.api.trantor.models.HTTPValidationError
import me.calebjones.spacelaunchnow.api.trantor.models.PaginatedResponseSpacecraftSummary
import me.calebjones.spacelaunchnow.api.trantor.models.SpacecraftFull

class SpacecraftApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SpacecraftApi
        //val apiInstance = SpacecraftApi()

        // to test getSpacecraftApiV1SpacecraftSpacecraftIdGet
        should("test getSpacecraftApiV1SpacecraftSpacecraftIdGet") {
            // uncomment below to test getSpacecraftApiV1SpacecraftSpacecraftIdGet
            //val spacecraftId : kotlin.Int = 56 // kotlin.Int | 
            //val result : SpacecraftFull = apiInstance.getSpacecraftApiV1SpacecraftSpacecraftIdGet(spacecraftId)
            //result shouldBe ("TODO")
        }

        // to test listSpacecraftApiV1SpacecraftGet
        should("test listSpacecraftApiV1SpacecraftGet") {
            // uncomment below to test listSpacecraftApiV1SpacecraftGet
            //val configId : kotlin.Int = 56 // kotlin.Int | Filter by spacecraft config id
            //val inSpace : kotlin.Boolean = true // kotlin.Boolean | Filter by currently-in-space
            //val isPlaceholder : kotlin.Boolean = true // kotlin.Boolean | Filter by placeholder status
            //val search : kotlin.String = search_example // kotlin.String | Search by name
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results per page
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of results to skip
            //val result : PaginatedResponseSpacecraftSummary = apiInstance.listSpacecraftApiV1SpacecraftGet(configId, inSpace, isPlaceholder, search, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
