/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.apis.SpacecraftConfigurationsApi
import me.calebjones.spacelaunchnow.api.trantor.models.HTTPValidationError
import me.calebjones.spacelaunchnow.api.trantor.models.PaginatedResponseSpacecraftConfigSummary
import me.calebjones.spacelaunchnow.api.trantor.models.SpacecraftConfigFull

class SpacecraftConfigurationsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SpacecraftConfigurationsApi
        //val apiInstance = SpacecraftConfigurationsApi()

        // to test getSpacecraftConfigurationApiV1SpacecraftConfigurationsConfigIdGet
        should("test getSpacecraftConfigurationApiV1SpacecraftConfigurationsConfigIdGet") {
            // uncomment below to test getSpacecraftConfigurationApiV1SpacecraftConfigurationsConfigIdGet
            //val configId : kotlin.Int = 56 // kotlin.Int | 
            //val result : SpacecraftConfigFull = apiInstance.getSpacecraftConfigurationApiV1SpacecraftConfigurationsConfigIdGet(configId)
            //result shouldBe ("TODO")
        }

        // to test listSpacecraftConfigurationsApiV1SpacecraftConfigurationsGet
        should("test listSpacecraftConfigurationsApiV1SpacecraftConfigurationsGet") {
            // uncomment below to test listSpacecraftConfigurationsApiV1SpacecraftConfigurationsGet
            //val agencyId : kotlin.Int = 56 // kotlin.Int | Filter by manufacturer agency id
            //val search : kotlin.String = search_example // kotlin.String | Search by name
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results per page
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of results to skip
            //val result : PaginatedResponseSpacecraftConfigSummary = apiInstance.listSpacecraftConfigurationsApiV1SpacecraftConfigurationsGet(agencyId, search, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
