/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.apis.UpdatesApi
import me.calebjones.spacelaunchnow.api.trantor.models.HTTPValidationError
import me.calebjones.spacelaunchnow.api.trantor.models.PaginatedResponseUpdateList

class UpdatesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdatesApi
        //val apiInstance = UpdatesApi()

        // to test listUpdatesApiV1UpdatesGet
        should("test listUpdatesApiV1UpdatesGet") {
            // uncomment below to test listUpdatesApiV1UpdatesGet
            //val programIds : kotlin.String = programIds_example // kotlin.String | Comma-separated program ids
            //val launchId : kotlin.String = launchId_example // kotlin.String | Launch id
            //val ordering : kotlin.String = ordering_example // kotlin.String | Order by `created_on`. Prefix - for descending. Unknown values fall back to -created_on.
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results per page
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of results to skip
            //val result : PaginatedResponseUpdateList = apiInstance.listUpdatesApiV1UpdatesGet(programIds, launchId, ordering, limit, offset)
            //result shouldBe ("TODO")
        }

    }
}
