/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.launchlibrary.apis.RocketsApi
import me.calebjones.spacelaunchnow.api.launchlibrary.models.PaginatedRocketStandaloneNormalList
import me.calebjones.spacelaunchnow.api.launchlibrary.models.RocketStandaloneDetailed

class RocketsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RocketsApi
        //val apiInstance = RocketsApi()

        // to test rocketsList
        should("test rocketsList") {
            // uncomment below to test rocketsList
            //val configurationFullName : kotlin.String = configurationFullName_example // kotlin.String | 
            //val configurationFullNameIcontains : kotlin.String = configurationFullNameIcontains_example // kotlin.String | 
            //val configurationIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Comma-separated launcher configuration IDs.
            //val configurationManufacturerName : kotlin.String = configurationManufacturerName_example // kotlin.String | 
            //val configurationManufacturerNameIcontains : kotlin.String = configurationManufacturerNameIcontains_example // kotlin.String | 
            //val configurationName : kotlin.String = configurationName_example // kotlin.String | 
            //val configurationNameIcontains : kotlin.String = configurationNameIcontains_example // kotlin.String | 
            //val configurationId : kotlin.Int = 56 // kotlin.Int | Single launcher configuration ID.
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results to return per page.
            //val offset : kotlin.Int = 56 // kotlin.Int | The initial index from which to return the results.
            //val ordering : kotlin.String = ordering_example // kotlin.String | Which field to use when ordering the results.
            //val search : kotlin.String = search_example // kotlin.String | A search term.
            //val result : PaginatedRocketStandaloneNormalList = apiInstance.rocketsList(configurationFullName, configurationFullNameIcontains, configurationIds, configurationManufacturerName, configurationManufacturerNameIcontains, configurationName, configurationNameIcontains, configurationId, id, limit, offset, ordering, search)
            //result shouldBe ("TODO")
        }

        // to test rocketsRetrieve
        should("test rocketsRetrieve") {
            // uncomment below to test rocketsRetrieve
            //val id : kotlin.Int = 56 // kotlin.Int | A unique integer value identifying this rocket.
            //val result : RocketStandaloneDetailed = apiInstance.rocketsRetrieve(id)
            //result shouldBe ("TODO")
        }

    }
}
