/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.launchlibrary.apis.StagesApi
import me.calebjones.spacelaunchnow.api.launchlibrary.models.PaginatedStageStandaloneNormalList
import me.calebjones.spacelaunchnow.api.launchlibrary.models.StageStandaloneDetailed

class StagesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StagesApi
        //val apiInstance = StagesApi()

        // to test stagesList
        should("test stagesList") {
            // uncomment below to test stagesList
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //val launcher : kotlin.Int = 56 // kotlin.Int | 
            //val launcherIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Comma-separated launcher IDs.
            //val launcherSerialNumber : kotlin.String = launcherSerialNumber_example // kotlin.String | 
            //val launcherSerialNumberIcontains : kotlin.String = launcherSerialNumberIcontains_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results to return per page.
            //val offset : kotlin.Int = 56 // kotlin.Int | The initial index from which to return the results.
            //val ordering : kotlin.String = ordering_example // kotlin.String | Which field to use when ordering the results.
            //val reused : kotlin.Boolean = true // kotlin.Boolean | 
            //val rocket : kotlin.Int = 56 // kotlin.Int | 
            //val rocketIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Comma-separated rocket IDs.
            //val search : kotlin.String = search_example // kotlin.String | A search term.
            //val type : kotlin.Int = 56 // kotlin.Int | 
            //val result : PaginatedStageStandaloneNormalList = apiInstance.stagesList(id, launcher, launcherIds, launcherSerialNumber, launcherSerialNumberIcontains, limit, offset, ordering, reused, rocket, rocketIds, search, type)
            //result shouldBe ("TODO")
        }

        // to test stagesRetrieve
        should("test stagesRetrieve") {
            // uncomment below to test stagesRetrieve
            //val id : kotlin.Int = 56 // kotlin.Int | A unique integer value identifying this first stage.
            //val result : StageStandaloneDetailed = apiInstance.stagesRetrieve(id)
            //result shouldBe ("TODO")
        }

    }
}
