/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.apis

import me.calebjones.spacelaunchnow.api.models.PadDetailed
import me.calebjones.spacelaunchnow.api.models.PaginatedPadDetailedList

import me.calebjones.spacelaunchnow.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class PadsApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * #### Filters Parameters - &#x60;active&#x60;, &#x60;agencies_ids&#x60;, &#x60;id&#x60;, &#x60;id__contains&#x60;, &#x60;latitude__gt&#x60;, &#x60;latitude__gte&#x60;, &#x60;latitude__lt&#x60;, &#x60;latitude__lte&#x60;, &#x60;location__id&#x60;, &#x60;location__name&#x60;, &#x60;location__name__contains&#x60;, &#x60;longitude__gt&#x60;, &#x60;longitude__gte&#x60;, &#x60;longitude__lt&#x60;, &#x60;longitude__lte&#x60;, &#x60;name&#x60;, &#x60;name__contains&#x60;, &#x60;orbital_launch_attempt_count&#x60;, &#x60;orbital_launch_attempt_count__gt&#x60;, &#x60;orbital_launch_attempt_count__gte&#x60;, &#x60;orbital_launch_attempt_count__lt&#x60;, &#x60;orbital_launch_attempt_count__lte&#x60;, &#x60;total_launch_count&#x60;, &#x60;total_launch_count__gt&#x60;, &#x60;total_launch_count__gte&#x60;, &#x60;total_launch_count__lt&#x60;, &#x60;total_launch_count__lte&#x60;  Example - [/pads/?location__id&#x3D;11](./?location__id&#x3D;11)  #### Search Fields searched - &#x60;location__name&#x60;, &#x60;name&#x60;, &#x60;orbital_launch_attempt_count&#x60;, &#x60;total_launch_count&#x60;  Example - [/pads/?search&#x3D;39A](./?search&#x3D;39A)  #### Ordering Fields - &#x60;id&#x60;, &#x60;location__id&#x60;, &#x60;location__name&#x60;, &#x60;name&#x60;, &#x60;orbital_launch_attempt_count&#x60;, &#x60;total_launch_count&#x60;  Example - [/pads/?ordering&#x3D;-orbital_launch_attempt_count](./?ordering&#x3D;-orbital_launch_attempt_count)  #### Number of results Use &#x60;limit&#x60; to control the number of objects in the response (max 100)  Example - [/pads/?limit&#x3D;2](./?limit&#x3D;2)  #### Format Switch to JSON output - [/pads/?format&#x3D;json](./?format&#x3D;json)  #### Help Find all the FAQs and support links on the documentation homepage - [spacelaunchnow.app/docs](https://spacelaunchnow.app/docs/)
     * @param active  (optional)
     * @param agenciesIds Multiple values may be separated by commas. (optional)
     * @param id  (optional)
     * @param idContains  (optional)
     * @param latitudeGt  (optional)
     * @param latitudeGte  (optional)
     * @param latitudeLt  (optional)
     * @param latitudeLte  (optional)
     * @param limit Number of results to return per page. (optional)
     * @param locationId  (optional)
     * @param locationName  (optional)
     * @param locationNameContains  (optional)
     * @param longitudeGt  (optional)
     * @param longitudeGte  (optional)
     * @param longitudeLt  (optional)
     * @param longitudeLte  (optional)
     * @param name  (optional)
     * @param nameContains  (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param orbitalLaunchAttemptCount  (optional)
     * @param orbitalLaunchAttemptCountGt  (optional)
     * @param orbitalLaunchAttemptCountGte  (optional)
     * @param orbitalLaunchAttemptCountLt  (optional)
     * @param orbitalLaunchAttemptCountLte  (optional)
     * @param ordering Which field to use when ordering the results. (optional)
     * @param search A search term. (optional)
     * @param totalLaunchCount  (optional)
     * @param totalLaunchCountGt  (optional)
     * @param totalLaunchCountGte  (optional)
     * @param totalLaunchCountLt  (optional)
     * @param totalLaunchCountLte  (optional)
     * @return PaginatedPadDetailedList
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun padsList(active: kotlin.Boolean? = null, agenciesIds: kotlin.collections.List<kotlin.Int>? = null, id: kotlin.Int? = null, idContains: kotlin.Int? = null, latitudeGt: kotlin.Float? = null, latitudeGte: kotlin.Float? = null, latitudeLt: kotlin.Float? = null, latitudeLte: kotlin.Float? = null, limit: kotlin.Int? = null, locationId: kotlin.Int? = null, locationName: kotlin.String? = null, locationNameContains: kotlin.String? = null, longitudeGt: kotlin.Float? = null, longitudeGte: kotlin.Float? = null, longitudeLt: kotlin.Float? = null, longitudeLte: kotlin.Float? = null, name: kotlin.String? = null, nameContains: kotlin.String? = null, offset: kotlin.Int? = null, orbitalLaunchAttemptCount: kotlin.Int? = null, orbitalLaunchAttemptCountGt: kotlin.Int? = null, orbitalLaunchAttemptCountGte: kotlin.Int? = null, orbitalLaunchAttemptCountLt: kotlin.Int? = null, orbitalLaunchAttemptCountLte: kotlin.Int? = null, ordering: kotlin.String? = null, search: kotlin.String? = null, totalLaunchCount: kotlin.Int? = null, totalLaunchCountGt: kotlin.Int? = null, totalLaunchCountGte: kotlin.Int? = null, totalLaunchCountLt: kotlin.Int? = null, totalLaunchCountLte: kotlin.Int? = null): HttpResponse<PaginatedPadDetailedList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "tokenAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        active?.apply { localVariableQuery["active"] = listOf("$active") }
        agenciesIds?.apply { localVariableQuery["agencies_ids"] = toMultiValue(this, "csv") }
        id?.apply { localVariableQuery["id"] = listOf("$id") }
        idContains?.apply { localVariableQuery["id__contains"] = listOf("$idContains") }
        latitudeGt?.apply { localVariableQuery["latitude__gt"] = listOf("$latitudeGt") }
        latitudeGte?.apply { localVariableQuery["latitude__gte"] = listOf("$latitudeGte") }
        latitudeLt?.apply { localVariableQuery["latitude__lt"] = listOf("$latitudeLt") }
        latitudeLte?.apply { localVariableQuery["latitude__lte"] = listOf("$latitudeLte") }
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        locationId?.apply { localVariableQuery["location__id"] = listOf("$locationId") }
        locationName?.apply { localVariableQuery["location__name"] = listOf("$locationName") }
        locationNameContains?.apply { localVariableQuery["location__name__contains"] = listOf("$locationNameContains") }
        longitudeGt?.apply { localVariableQuery["longitude__gt"] = listOf("$longitudeGt") }
        longitudeGte?.apply { localVariableQuery["longitude__gte"] = listOf("$longitudeGte") }
        longitudeLt?.apply { localVariableQuery["longitude__lt"] = listOf("$longitudeLt") }
        longitudeLte?.apply { localVariableQuery["longitude__lte"] = listOf("$longitudeLte") }
        name?.apply { localVariableQuery["name"] = listOf("$name") }
        nameContains?.apply { localVariableQuery["name__contains"] = listOf("$nameContains") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        orbitalLaunchAttemptCount?.apply { localVariableQuery["orbital_launch_attempt_count"] = listOf("$orbitalLaunchAttemptCount") }
        orbitalLaunchAttemptCountGt?.apply { localVariableQuery["orbital_launch_attempt_count__gt"] = listOf("$orbitalLaunchAttemptCountGt") }
        orbitalLaunchAttemptCountGte?.apply { localVariableQuery["orbital_launch_attempt_count__gte"] = listOf("$orbitalLaunchAttemptCountGte") }
        orbitalLaunchAttemptCountLt?.apply { localVariableQuery["orbital_launch_attempt_count__lt"] = listOf("$orbitalLaunchAttemptCountLt") }
        orbitalLaunchAttemptCountLte?.apply { localVariableQuery["orbital_launch_attempt_count__lte"] = listOf("$orbitalLaunchAttemptCountLte") }
        ordering?.apply { localVariableQuery["ordering"] = listOf("$ordering") }
        search?.apply { localVariableQuery["search"] = listOf("$search") }
        totalLaunchCount?.apply { localVariableQuery["total_launch_count"] = listOf("$totalLaunchCount") }
        totalLaunchCountGt?.apply { localVariableQuery["total_launch_count__gt"] = listOf("$totalLaunchCountGt") }
        totalLaunchCountGte?.apply { localVariableQuery["total_launch_count__gte"] = listOf("$totalLaunchCountGte") }
        totalLaunchCountLt?.apply { localVariableQuery["total_launch_count__lt"] = listOf("$totalLaunchCountLt") }
        totalLaunchCountLte?.apply { localVariableQuery["total_launch_count__lte"] = listOf("$totalLaunchCountLte") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/ll/2.4.0/pads/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * #### Filters Parameters - &#x60;active&#x60;, &#x60;agencies_ids&#x60;, &#x60;id&#x60;, &#x60;id__contains&#x60;, &#x60;latitude__gt&#x60;, &#x60;latitude__gte&#x60;, &#x60;latitude__lt&#x60;, &#x60;latitude__lte&#x60;, &#x60;location__id&#x60;, &#x60;location__name&#x60;, &#x60;location__name__contains&#x60;, &#x60;longitude__gt&#x60;, &#x60;longitude__gte&#x60;, &#x60;longitude__lt&#x60;, &#x60;longitude__lte&#x60;, &#x60;name&#x60;, &#x60;name__contains&#x60;, &#x60;orbital_launch_attempt_count&#x60;, &#x60;orbital_launch_attempt_count__gt&#x60;, &#x60;orbital_launch_attempt_count__gte&#x60;, &#x60;orbital_launch_attempt_count__lt&#x60;, &#x60;orbital_launch_attempt_count__lte&#x60;, &#x60;total_launch_count&#x60;, &#x60;total_launch_count__gt&#x60;, &#x60;total_launch_count__gte&#x60;, &#x60;total_launch_count__lt&#x60;, &#x60;total_launch_count__lte&#x60;  Example - [/pads/?location__id&#x3D;11](./?location__id&#x3D;11)  #### Search Fields searched - &#x60;location__name&#x60;, &#x60;name&#x60;, &#x60;orbital_launch_attempt_count&#x60;, &#x60;total_launch_count&#x60;  Example - [/pads/?search&#x3D;39A](./?search&#x3D;39A)  #### Ordering Fields - &#x60;id&#x60;, &#x60;location__id&#x60;, &#x60;location__name&#x60;, &#x60;name&#x60;, &#x60;orbital_launch_attempt_count&#x60;, &#x60;total_launch_count&#x60;  Example - [/pads/?ordering&#x3D;-orbital_launch_attempt_count](./?ordering&#x3D;-orbital_launch_attempt_count)  #### Number of results Use &#x60;limit&#x60; to control the number of objects in the response (max 100)  Example - [/pads/?limit&#x3D;2](./?limit&#x3D;2)  #### Format Switch to JSON output - [/pads/?format&#x3D;json](./?format&#x3D;json)  #### Help Find all the FAQs and support links on the documentation homepage - [spacelaunchnow.app/docs](https://spacelaunchnow.app/docs/)
     * @param id A unique integer value identifying this Pad.
     * @return PadDetailed
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun padsRetrieve(id: kotlin.Int): HttpResponse<PadDetailed> {

        val localVariableAuthNames = listOf<String>("basicAuth", "tokenAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/ll/2.4.0/pads/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


}
