/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.apis

import me.calebjones.spacelaunchnow.api.launchlibrary.models.LauncherDetailed
import me.calebjones.spacelaunchnow.api.launchlibrary.models.PaginatedLauncherDetailedList
import me.calebjones.spacelaunchnow.api.launchlibrary.models.PaginatedLauncherMiniList
import me.calebjones.spacelaunchnow.api.launchlibrary.models.PaginatedLauncherNormalList

import me.calebjones.spacelaunchnow.api.launchlibrary.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class LaunchersApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * #### Filters Parameters - &#x60;attempted_landings&#x60;, &#x60;attempted_landings__gt&#x60;, &#x60;attempted_landings__gte&#x60;, &#x60;attempted_landings__lt&#x60;, &#x60;attempted_landings__lte&#x60;, &#x60;first_launch_date&#x60;, &#x60;first_launch_date__day&#x60;, &#x60;first_launch_date__month&#x60;, &#x60;first_launch_date__year&#x60;, &#x60;flight_proven&#x60;, &#x60;flights&#x60;, &#x60;flights__gt&#x60;, &#x60;flights__gte&#x60;, &#x60;flights__lt&#x60;, &#x60;flights__lte&#x60;, &#x60;id&#x60;, &#x60;id__contains&#x60;, &#x60;is_placeholder&#x60;, &#x60;last_launch_date&#x60;, &#x60;launcher_config__ids&#x60;, &#x60;launcher_config__manufacturer__name&#x60;, &#x60;launcher_config__manufacturer__name__contains&#x60;, &#x60;serial_number&#x60;, &#x60;serial_number__contains&#x60;, &#x60;status&#x60;, &#x60;successful_landings&#x60;, &#x60;successful_landings__gt&#x60;, &#x60;successful_landings__gte&#x60;, &#x60;successful_landings__lt&#x60;, &#x60;successful_landings__lte&#x60;  Example - [/launchers/detailed/?is_placeholder&#x3D;True](./?is_placeholder&#x3D;True)  #### Search Fields searched - &#x60;serial_number&#x60;, &#x60;status__name&#x60;  Example - [/launchers/detailed/?search&#x3D;B1048](./?search&#x3D;B1048)  #### Ordering Fields - &#x60;attempted_landings&#x60;, &#x60;flight_proven&#x60;, &#x60;flights&#x60;, &#x60;id&#x60;, &#x60;successful_landings&#x60;  Example - [/launchers/detailed/?ordering&#x3D;-flights](./?ordering&#x3D;-flights)  #### Number of results Use &#x60;limit&#x60; to control the number of objects in the response (max 100)  Example - [/launchers/detailed/?limit&#x3D;2](./?limit&#x3D;2)  #### Format Switch to JSON output - [/launchers/detailed/?format&#x3D;json](./?format&#x3D;json)  #### Help Find all the FAQs and support links on the documentation homepage - [spacelaunchnow.app/docs](https://spacelaunchnow.app/docs/)
     * @param attemptedLandings  (optional)
     * @param attemptedLandingsGt  (optional)
     * @param attemptedLandingsGte  (optional)
     * @param attemptedLandingsLt  (optional)
     * @param attemptedLandingsLte  (optional)
     * @param firstLaunchDate  (optional)
     * @param firstLaunchDateDay Comma-separated first launch date days. (optional)
     * @param firstLaunchDateMonth Comma-separated first launch date months. (optional)
     * @param firstLaunchDateYear Comma-separated first launch date years. (optional)
     * @param flightProven  (optional)
     * @param flights  (optional)
     * @param flightsGt  (optional)
     * @param flightsGte  (optional)
     * @param flightsLt  (optional)
     * @param flightsLte  (optional)
     * @param id  (optional)
     * @param idContains  (optional)
     * @param isPlaceholder  (optional)
     * @param lastLaunchDate  (optional)
     * @param launcherConfigIds Comma-separated launcher config IDs. (optional)
     * @param launcherConfigManufacturerName  (optional)
     * @param launcherConfigManufacturerNameContains  (optional)
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param ordering Which field to use when ordering the results. (optional)
     * @param search A search term. (optional)
     * @param serialNumber  (optional)
     * @param serialNumberContains  (optional)
     * @param status  (optional)
     * @param successfulLandings  (optional)
     * @param successfulLandingsGt  (optional)
     * @param successfulLandingsGte  (optional)
     * @param successfulLandingsLt  (optional)
     * @param successfulLandingsLte  (optional)
     * @return PaginatedLauncherDetailedList
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun launchersDetailedList(attemptedLandings: kotlin.Int? = null, attemptedLandingsGt: kotlin.Int? = null, attemptedLandingsGte: kotlin.Int? = null, attemptedLandingsLt: kotlin.Int? = null, attemptedLandingsLte: kotlin.Int? = null, firstLaunchDate: kotlin.time.Instant? = null, firstLaunchDateDay: kotlin.collections.List<kotlin.Double>? = null, firstLaunchDateMonth: kotlin.collections.List<kotlin.Double>? = null, firstLaunchDateYear: kotlin.collections.List<kotlin.Double>? = null, flightProven: kotlin.Boolean? = null, flights: kotlin.Int? = null, flightsGt: kotlin.Int? = null, flightsGte: kotlin.Int? = null, flightsLt: kotlin.Int? = null, flightsLte: kotlin.Int? = null, id: kotlin.Int? = null, idContains: kotlin.Int? = null, isPlaceholder: kotlin.Boolean? = null, lastLaunchDate: kotlin.time.Instant? = null, launcherConfigIds: kotlin.collections.List<kotlin.Int>? = null, launcherConfigManufacturerName: kotlin.String? = null, launcherConfigManufacturerNameContains: kotlin.String? = null, limit: kotlin.Int? = null, offset: kotlin.Int? = null, ordering: kotlin.String? = null, search: kotlin.String? = null, serialNumber: kotlin.String? = null, serialNumberContains: kotlin.String? = null, status: kotlin.Int? = null, successfulLandings: kotlin.Int? = null, successfulLandingsGt: kotlin.Int? = null, successfulLandingsGte: kotlin.Int? = null, successfulLandingsLt: kotlin.Int? = null, successfulLandingsLte: kotlin.Int? = null): HttpResponse<PaginatedLauncherDetailedList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "tokenAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        attemptedLandings?.apply { localVariableQuery["attempted_landings"] = listOf("$attemptedLandings") }
        attemptedLandingsGt?.apply { localVariableQuery["attempted_landings__gt"] = listOf("$attemptedLandingsGt") }
        attemptedLandingsGte?.apply { localVariableQuery["attempted_landings__gte"] = listOf("$attemptedLandingsGte") }
        attemptedLandingsLt?.apply { localVariableQuery["attempted_landings__lt"] = listOf("$attemptedLandingsLt") }
        attemptedLandingsLte?.apply { localVariableQuery["attempted_landings__lte"] = listOf("$attemptedLandingsLte") }
        firstLaunchDate?.apply { localVariableQuery["first_launch_date"] = listOf("$firstLaunchDate") }
        firstLaunchDateDay?.apply { localVariableQuery["first_launch_date__day"] = toMultiValue(this, "csv") }
        firstLaunchDateMonth?.apply { localVariableQuery["first_launch_date__month"] = toMultiValue(this, "csv") }
        firstLaunchDateYear?.apply { localVariableQuery["first_launch_date__year"] = toMultiValue(this, "csv") }
        flightProven?.apply { localVariableQuery["flight_proven"] = listOf("$flightProven") }
        flights?.apply { localVariableQuery["flights"] = listOf("$flights") }
        flightsGt?.apply { localVariableQuery["flights__gt"] = listOf("$flightsGt") }
        flightsGte?.apply { localVariableQuery["flights__gte"] = listOf("$flightsGte") }
        flightsLt?.apply { localVariableQuery["flights__lt"] = listOf("$flightsLt") }
        flightsLte?.apply { localVariableQuery["flights__lte"] = listOf("$flightsLte") }
        id?.apply { localVariableQuery["id"] = listOf("$id") }
        idContains?.apply { localVariableQuery["id__contains"] = listOf("$idContains") }
        isPlaceholder?.apply { localVariableQuery["is_placeholder"] = listOf("$isPlaceholder") }
        lastLaunchDate?.apply { localVariableQuery["last_launch_date"] = listOf("$lastLaunchDate") }
        launcherConfigIds?.apply { localVariableQuery["launcher_config__ids"] = toMultiValue(this, "csv") }
        launcherConfigManufacturerName?.apply { localVariableQuery["launcher_config__manufacturer__name"] = listOf("$launcherConfigManufacturerName") }
        launcherConfigManufacturerNameContains?.apply { localVariableQuery["launcher_config__manufacturer__name__contains"] = listOf("$launcherConfigManufacturerNameContains") }
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        ordering?.apply { localVariableQuery["ordering"] = listOf("$ordering") }
        search?.apply { localVariableQuery["search"] = listOf("$search") }
        serialNumber?.apply { localVariableQuery["serial_number"] = listOf("$serialNumber") }
        serialNumberContains?.apply { localVariableQuery["serial_number__contains"] = listOf("$serialNumberContains") }
        status?.apply { localVariableQuery["status"] = listOf("$status") }
        successfulLandings?.apply { localVariableQuery["successful_landings"] = listOf("$successfulLandings") }
        successfulLandingsGt?.apply { localVariableQuery["successful_landings__gt"] = listOf("$successfulLandingsGt") }
        successfulLandingsGte?.apply { localVariableQuery["successful_landings__gte"] = listOf("$successfulLandingsGte") }
        successfulLandingsLt?.apply { localVariableQuery["successful_landings__lt"] = listOf("$successfulLandingsLt") }
        successfulLandingsLte?.apply { localVariableQuery["successful_landings__lte"] = listOf("$successfulLandingsLte") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/ll/2.4.0/launchers/detailed/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * #### Filters Parameters - &#x60;attempted_landings&#x60;, &#x60;attempted_landings__gt&#x60;, &#x60;attempted_landings__gte&#x60;, &#x60;attempted_landings__lt&#x60;, &#x60;attempted_landings__lte&#x60;, &#x60;first_launch_date&#x60;, &#x60;first_launch_date__day&#x60;, &#x60;first_launch_date__month&#x60;, &#x60;first_launch_date__year&#x60;, &#x60;flight_proven&#x60;, &#x60;flights&#x60;, &#x60;flights__gt&#x60;, &#x60;flights__gte&#x60;, &#x60;flights__lt&#x60;, &#x60;flights__lte&#x60;, &#x60;id&#x60;, &#x60;id__contains&#x60;, &#x60;is_placeholder&#x60;, &#x60;last_launch_date&#x60;, &#x60;launcher_config__ids&#x60;, &#x60;launcher_config__manufacturer__name&#x60;, &#x60;launcher_config__manufacturer__name__contains&#x60;, &#x60;serial_number&#x60;, &#x60;serial_number__contains&#x60;, &#x60;status&#x60;, &#x60;successful_landings&#x60;, &#x60;successful_landings__gt&#x60;, &#x60;successful_landings__gte&#x60;, &#x60;successful_landings__lt&#x60;, &#x60;successful_landings__lte&#x60;  Example - [/launchers/?is_placeholder&#x3D;True](./?is_placeholder&#x3D;True)  #### Search Fields searched - &#x60;serial_number&#x60;, &#x60;status__name&#x60;  Example - [/launchers/?search&#x3D;B1048](./?search&#x3D;B1048)  #### Ordering Fields - &#x60;attempted_landings&#x60;, &#x60;flight_proven&#x60;, &#x60;flights&#x60;, &#x60;id&#x60;, &#x60;successful_landings&#x60;  Example - [/launchers/?ordering&#x3D;-flights](./?ordering&#x3D;-flights)  #### Number of results Use &#x60;limit&#x60; to control the number of objects in the response (max 100)  Example - [/launchers/?limit&#x3D;2](./?limit&#x3D;2)  #### Format Switch to JSON output - [/launchers/?format&#x3D;json](./?format&#x3D;json)  #### Help Find all the FAQs and support links on the documentation homepage - [spacelaunchnow.app/docs](https://spacelaunchnow.app/docs/)
     * @param attemptedLandings  (optional)
     * @param attemptedLandingsGt  (optional)
     * @param attemptedLandingsGte  (optional)
     * @param attemptedLandingsLt  (optional)
     * @param attemptedLandingsLte  (optional)
     * @param firstLaunchDate  (optional)
     * @param firstLaunchDateDay Comma-separated first launch date days. (optional)
     * @param firstLaunchDateMonth Comma-separated first launch date months. (optional)
     * @param firstLaunchDateYear Comma-separated first launch date years. (optional)
     * @param flightProven  (optional)
     * @param flights  (optional)
     * @param flightsGt  (optional)
     * @param flightsGte  (optional)
     * @param flightsLt  (optional)
     * @param flightsLte  (optional)
     * @param id  (optional)
     * @param idContains  (optional)
     * @param isPlaceholder  (optional)
     * @param lastLaunchDate  (optional)
     * @param launcherConfigIds Comma-separated launcher config IDs. (optional)
     * @param launcherConfigManufacturerName  (optional)
     * @param launcherConfigManufacturerNameContains  (optional)
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param ordering Which field to use when ordering the results. (optional)
     * @param search A search term. (optional)
     * @param serialNumber  (optional)
     * @param serialNumberContains  (optional)
     * @param status  (optional)
     * @param successfulLandings  (optional)
     * @param successfulLandingsGt  (optional)
     * @param successfulLandingsGte  (optional)
     * @param successfulLandingsLt  (optional)
     * @param successfulLandingsLte  (optional)
     * @return PaginatedLauncherNormalList
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun launchersList(attemptedLandings: kotlin.Int? = null, attemptedLandingsGt: kotlin.Int? = null, attemptedLandingsGte: kotlin.Int? = null, attemptedLandingsLt: kotlin.Int? = null, attemptedLandingsLte: kotlin.Int? = null, firstLaunchDate: kotlin.time.Instant? = null, firstLaunchDateDay: kotlin.collections.List<kotlin.Double>? = null, firstLaunchDateMonth: kotlin.collections.List<kotlin.Double>? = null, firstLaunchDateYear: kotlin.collections.List<kotlin.Double>? = null, flightProven: kotlin.Boolean? = null, flights: kotlin.Int? = null, flightsGt: kotlin.Int? = null, flightsGte: kotlin.Int? = null, flightsLt: kotlin.Int? = null, flightsLte: kotlin.Int? = null, id: kotlin.Int? = null, idContains: kotlin.Int? = null, isPlaceholder: kotlin.Boolean? = null, lastLaunchDate: kotlin.time.Instant? = null, launcherConfigIds: kotlin.collections.List<kotlin.Int>? = null, launcherConfigManufacturerName: kotlin.String? = null, launcherConfigManufacturerNameContains: kotlin.String? = null, limit: kotlin.Int? = null, offset: kotlin.Int? = null, ordering: kotlin.String? = null, search: kotlin.String? = null, serialNumber: kotlin.String? = null, serialNumberContains: kotlin.String? = null, status: kotlin.Int? = null, successfulLandings: kotlin.Int? = null, successfulLandingsGt: kotlin.Int? = null, successfulLandingsGte: kotlin.Int? = null, successfulLandingsLt: kotlin.Int? = null, successfulLandingsLte: kotlin.Int? = null): HttpResponse<PaginatedLauncherNormalList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "tokenAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        attemptedLandings?.apply { localVariableQuery["attempted_landings"] = listOf("$attemptedLandings") }
        attemptedLandingsGt?.apply { localVariableQuery["attempted_landings__gt"] = listOf("$attemptedLandingsGt") }
        attemptedLandingsGte?.apply { localVariableQuery["attempted_landings__gte"] = listOf("$attemptedLandingsGte") }
        attemptedLandingsLt?.apply { localVariableQuery["attempted_landings__lt"] = listOf("$attemptedLandingsLt") }
        attemptedLandingsLte?.apply { localVariableQuery["attempted_landings__lte"] = listOf("$attemptedLandingsLte") }
        firstLaunchDate?.apply { localVariableQuery["first_launch_date"] = listOf("$firstLaunchDate") }
        firstLaunchDateDay?.apply { localVariableQuery["first_launch_date__day"] = toMultiValue(this, "csv") }
        firstLaunchDateMonth?.apply { localVariableQuery["first_launch_date__month"] = toMultiValue(this, "csv") }
        firstLaunchDateYear?.apply { localVariableQuery["first_launch_date__year"] = toMultiValue(this, "csv") }
        flightProven?.apply { localVariableQuery["flight_proven"] = listOf("$flightProven") }
        flights?.apply { localVariableQuery["flights"] = listOf("$flights") }
        flightsGt?.apply { localVariableQuery["flights__gt"] = listOf("$flightsGt") }
        flightsGte?.apply { localVariableQuery["flights__gte"] = listOf("$flightsGte") }
        flightsLt?.apply { localVariableQuery["flights__lt"] = listOf("$flightsLt") }
        flightsLte?.apply { localVariableQuery["flights__lte"] = listOf("$flightsLte") }
        id?.apply { localVariableQuery["id"] = listOf("$id") }
        idContains?.apply { localVariableQuery["id__contains"] = listOf("$idContains") }
        isPlaceholder?.apply { localVariableQuery["is_placeholder"] = listOf("$isPlaceholder") }
        lastLaunchDate?.apply { localVariableQuery["last_launch_date"] = listOf("$lastLaunchDate") }
        launcherConfigIds?.apply { localVariableQuery["launcher_config__ids"] = toMultiValue(this, "csv") }
        launcherConfigManufacturerName?.apply { localVariableQuery["launcher_config__manufacturer__name"] = listOf("$launcherConfigManufacturerName") }
        launcherConfigManufacturerNameContains?.apply { localVariableQuery["launcher_config__manufacturer__name__contains"] = listOf("$launcherConfigManufacturerNameContains") }
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        ordering?.apply { localVariableQuery["ordering"] = listOf("$ordering") }
        search?.apply { localVariableQuery["search"] = listOf("$search") }
        serialNumber?.apply { localVariableQuery["serial_number"] = listOf("$serialNumber") }
        serialNumberContains?.apply { localVariableQuery["serial_number__contains"] = listOf("$serialNumberContains") }
        status?.apply { localVariableQuery["status"] = listOf("$status") }
        successfulLandings?.apply { localVariableQuery["successful_landings"] = listOf("$successfulLandings") }
        successfulLandingsGt?.apply { localVariableQuery["successful_landings__gt"] = listOf("$successfulLandingsGt") }
        successfulLandingsGte?.apply { localVariableQuery["successful_landings__gte"] = listOf("$successfulLandingsGte") }
        successfulLandingsLt?.apply { localVariableQuery["successful_landings__lt"] = listOf("$successfulLandingsLt") }
        successfulLandingsLte?.apply { localVariableQuery["successful_landings__lte"] = listOf("$successfulLandingsLte") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/ll/2.4.0/launchers/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * #### Filters Parameters - &#x60;attempted_landings&#x60;, &#x60;attempted_landings__gt&#x60;, &#x60;attempted_landings__gte&#x60;, &#x60;attempted_landings__lt&#x60;, &#x60;attempted_landings__lte&#x60;, &#x60;first_launch_date&#x60;, &#x60;first_launch_date__day&#x60;, &#x60;first_launch_date__month&#x60;, &#x60;first_launch_date__year&#x60;, &#x60;flight_proven&#x60;, &#x60;flights&#x60;, &#x60;flights__gt&#x60;, &#x60;flights__gte&#x60;, &#x60;flights__lt&#x60;, &#x60;flights__lte&#x60;, &#x60;id&#x60;, &#x60;id__contains&#x60;, &#x60;is_placeholder&#x60;, &#x60;last_launch_date&#x60;, &#x60;launcher_config__ids&#x60;, &#x60;launcher_config__manufacturer__name&#x60;, &#x60;launcher_config__manufacturer__name__contains&#x60;, &#x60;serial_number&#x60;, &#x60;serial_number__contains&#x60;, &#x60;status&#x60;, &#x60;successful_landings&#x60;, &#x60;successful_landings__gt&#x60;, &#x60;successful_landings__gte&#x60;, &#x60;successful_landings__lt&#x60;, &#x60;successful_landings__lte&#x60;  Example - [/launchers/mini/?is_placeholder&#x3D;True](./?is_placeholder&#x3D;True)  #### Search Fields searched - &#x60;serial_number&#x60;, &#x60;status__name&#x60;  Example - [/launchers/mini/?search&#x3D;B1048](./?search&#x3D;B1048)  #### Ordering Fields - &#x60;attempted_landings&#x60;, &#x60;flight_proven&#x60;, &#x60;flights&#x60;, &#x60;id&#x60;, &#x60;successful_landings&#x60;  Example - [/launchers/mini/?ordering&#x3D;-flights](./?ordering&#x3D;-flights)  #### Number of results Use &#x60;limit&#x60; to control the number of objects in the response (max 100)  Example - [/launchers/mini/?limit&#x3D;2](./?limit&#x3D;2)  #### Format Switch to JSON output - [/launchers/mini/?format&#x3D;json](./?format&#x3D;json)  #### Help Find all the FAQs and support links on the documentation homepage - [spacelaunchnow.app/docs](https://spacelaunchnow.app/docs/)
     * @param attemptedLandings  (optional)
     * @param attemptedLandingsGt  (optional)
     * @param attemptedLandingsGte  (optional)
     * @param attemptedLandingsLt  (optional)
     * @param attemptedLandingsLte  (optional)
     * @param firstLaunchDate  (optional)
     * @param firstLaunchDateDay Comma-separated first launch date days. (optional)
     * @param firstLaunchDateMonth Comma-separated first launch date months. (optional)
     * @param firstLaunchDateYear Comma-separated first launch date years. (optional)
     * @param flightProven  (optional)
     * @param flights  (optional)
     * @param flightsGt  (optional)
     * @param flightsGte  (optional)
     * @param flightsLt  (optional)
     * @param flightsLte  (optional)
     * @param id  (optional)
     * @param idContains  (optional)
     * @param isPlaceholder  (optional)
     * @param lastLaunchDate  (optional)
     * @param launcherConfigIds Comma-separated launcher config IDs. (optional)
     * @param launcherConfigManufacturerName  (optional)
     * @param launcherConfigManufacturerNameContains  (optional)
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param ordering Which field to use when ordering the results. (optional)
     * @param search A search term. (optional)
     * @param serialNumber  (optional)
     * @param serialNumberContains  (optional)
     * @param status  (optional)
     * @param successfulLandings  (optional)
     * @param successfulLandingsGt  (optional)
     * @param successfulLandingsGte  (optional)
     * @param successfulLandingsLt  (optional)
     * @param successfulLandingsLte  (optional)
     * @return PaginatedLauncherMiniList
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun launchersMiniList(attemptedLandings: kotlin.Int? = null, attemptedLandingsGt: kotlin.Int? = null, attemptedLandingsGte: kotlin.Int? = null, attemptedLandingsLt: kotlin.Int? = null, attemptedLandingsLte: kotlin.Int? = null, firstLaunchDate: kotlin.time.Instant? = null, firstLaunchDateDay: kotlin.collections.List<kotlin.Double>? = null, firstLaunchDateMonth: kotlin.collections.List<kotlin.Double>? = null, firstLaunchDateYear: kotlin.collections.List<kotlin.Double>? = null, flightProven: kotlin.Boolean? = null, flights: kotlin.Int? = null, flightsGt: kotlin.Int? = null, flightsGte: kotlin.Int? = null, flightsLt: kotlin.Int? = null, flightsLte: kotlin.Int? = null, id: kotlin.Int? = null, idContains: kotlin.Int? = null, isPlaceholder: kotlin.Boolean? = null, lastLaunchDate: kotlin.time.Instant? = null, launcherConfigIds: kotlin.collections.List<kotlin.Int>? = null, launcherConfigManufacturerName: kotlin.String? = null, launcherConfigManufacturerNameContains: kotlin.String? = null, limit: kotlin.Int? = null, offset: kotlin.Int? = null, ordering: kotlin.String? = null, search: kotlin.String? = null, serialNumber: kotlin.String? = null, serialNumberContains: kotlin.String? = null, status: kotlin.Int? = null, successfulLandings: kotlin.Int? = null, successfulLandingsGt: kotlin.Int? = null, successfulLandingsGte: kotlin.Int? = null, successfulLandingsLt: kotlin.Int? = null, successfulLandingsLte: kotlin.Int? = null): HttpResponse<PaginatedLauncherMiniList> {

        val localVariableAuthNames = listOf<String>("basicAuth", "tokenAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        attemptedLandings?.apply { localVariableQuery["attempted_landings"] = listOf("$attemptedLandings") }
        attemptedLandingsGt?.apply { localVariableQuery["attempted_landings__gt"] = listOf("$attemptedLandingsGt") }
        attemptedLandingsGte?.apply { localVariableQuery["attempted_landings__gte"] = listOf("$attemptedLandingsGte") }
        attemptedLandingsLt?.apply { localVariableQuery["attempted_landings__lt"] = listOf("$attemptedLandingsLt") }
        attemptedLandingsLte?.apply { localVariableQuery["attempted_landings__lte"] = listOf("$attemptedLandingsLte") }
        firstLaunchDate?.apply { localVariableQuery["first_launch_date"] = listOf("$firstLaunchDate") }
        firstLaunchDateDay?.apply { localVariableQuery["first_launch_date__day"] = toMultiValue(this, "csv") }
        firstLaunchDateMonth?.apply { localVariableQuery["first_launch_date__month"] = toMultiValue(this, "csv") }
        firstLaunchDateYear?.apply { localVariableQuery["first_launch_date__year"] = toMultiValue(this, "csv") }
        flightProven?.apply { localVariableQuery["flight_proven"] = listOf("$flightProven") }
        flights?.apply { localVariableQuery["flights"] = listOf("$flights") }
        flightsGt?.apply { localVariableQuery["flights__gt"] = listOf("$flightsGt") }
        flightsGte?.apply { localVariableQuery["flights__gte"] = listOf("$flightsGte") }
        flightsLt?.apply { localVariableQuery["flights__lt"] = listOf("$flightsLt") }
        flightsLte?.apply { localVariableQuery["flights__lte"] = listOf("$flightsLte") }
        id?.apply { localVariableQuery["id"] = listOf("$id") }
        idContains?.apply { localVariableQuery["id__contains"] = listOf("$idContains") }
        isPlaceholder?.apply { localVariableQuery["is_placeholder"] = listOf("$isPlaceholder") }
        lastLaunchDate?.apply { localVariableQuery["last_launch_date"] = listOf("$lastLaunchDate") }
        launcherConfigIds?.apply { localVariableQuery["launcher_config__ids"] = toMultiValue(this, "csv") }
        launcherConfigManufacturerName?.apply { localVariableQuery["launcher_config__manufacturer__name"] = listOf("$launcherConfigManufacturerName") }
        launcherConfigManufacturerNameContains?.apply { localVariableQuery["launcher_config__manufacturer__name__contains"] = listOf("$launcherConfigManufacturerNameContains") }
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        ordering?.apply { localVariableQuery["ordering"] = listOf("$ordering") }
        search?.apply { localVariableQuery["search"] = listOf("$search") }
        serialNumber?.apply { localVariableQuery["serial_number"] = listOf("$serialNumber") }
        serialNumberContains?.apply { localVariableQuery["serial_number__contains"] = listOf("$serialNumberContains") }
        status?.apply { localVariableQuery["status"] = listOf("$status") }
        successfulLandings?.apply { localVariableQuery["successful_landings"] = listOf("$successfulLandings") }
        successfulLandingsGt?.apply { localVariableQuery["successful_landings__gt"] = listOf("$successfulLandingsGt") }
        successfulLandingsGte?.apply { localVariableQuery["successful_landings__gte"] = listOf("$successfulLandingsGte") }
        successfulLandingsLt?.apply { localVariableQuery["successful_landings__lt"] = listOf("$successfulLandingsLt") }
        successfulLandingsLte?.apply { localVariableQuery["successful_landings__lte"] = listOf("$successfulLandingsLte") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/ll/2.4.0/launchers/mini/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * #### Filters Parameters - &#x60;attempted_landings&#x60;, &#x60;attempted_landings__gt&#x60;, &#x60;attempted_landings__gte&#x60;, &#x60;attempted_landings__lt&#x60;, &#x60;attempted_landings__lte&#x60;, &#x60;first_launch_date&#x60;, &#x60;first_launch_date__day&#x60;, &#x60;first_launch_date__month&#x60;, &#x60;first_launch_date__year&#x60;, &#x60;flight_proven&#x60;, &#x60;flights&#x60;, &#x60;flights__gt&#x60;, &#x60;flights__gte&#x60;, &#x60;flights__lt&#x60;, &#x60;flights__lte&#x60;, &#x60;id&#x60;, &#x60;id__contains&#x60;, &#x60;is_placeholder&#x60;, &#x60;last_launch_date&#x60;, &#x60;launcher_config__ids&#x60;, &#x60;launcher_config__manufacturer__name&#x60;, &#x60;launcher_config__manufacturer__name__contains&#x60;, &#x60;serial_number&#x60;, &#x60;serial_number__contains&#x60;, &#x60;status&#x60;, &#x60;successful_landings&#x60;, &#x60;successful_landings__gt&#x60;, &#x60;successful_landings__gte&#x60;, &#x60;successful_landings__lt&#x60;, &#x60;successful_landings__lte&#x60;  Example - [/launchers/?is_placeholder&#x3D;True](./?is_placeholder&#x3D;True)  #### Search Fields searched - &#x60;serial_number&#x60;, &#x60;status__name&#x60;  Example - [/launchers/?search&#x3D;B1048](./?search&#x3D;B1048)  #### Ordering Fields - &#x60;attempted_landings&#x60;, &#x60;flight_proven&#x60;, &#x60;flights&#x60;, &#x60;id&#x60;, &#x60;successful_landings&#x60;  Example - [/launchers/?ordering&#x3D;-flights](./?ordering&#x3D;-flights)  #### Number of results Use &#x60;limit&#x60; to control the number of objects in the response (max 100)  Example - [/launchers/?limit&#x3D;2](./?limit&#x3D;2)  #### Format Switch to JSON output - [/launchers/?format&#x3D;json](./?format&#x3D;json)  #### Help Find all the FAQs and support links on the documentation homepage - [spacelaunchnow.app/docs](https://spacelaunchnow.app/docs/)
     * @param id A unique integer value identifying this Launch Vehicle.
     * @return LauncherDetailed
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun launchersRetrieve(id: kotlin.Int): HttpResponse<LauncherDetailed> {

        val localVariableAuthNames = listOf<String>("basicAuth", "tokenAuth", "cookieAuth")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/ll/2.4.0/launchers/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


}
