/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.client.apis

import me.calebjones.spacelaunchnow.api.client.models.ExpeditionDetailed
import me.calebjones.spacelaunchnow.api.client.models.PaginatedPolymorphicExpeditionEndpointList

import me.calebjones.spacelaunchnow.api.client.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class ExpeditionsApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * #### Modes Levels of detail in the response - &#x60;normal&#x60;, &#x60;detailed&#x60;  Example - [/expeditions/?mode&#x3D;detailed](./?mode&#x3D;detailed)  #### Filters Parameters - &#x60;crew__astronaut&#x60;, &#x60;crew__astronaut__agency&#x60;, &#x60;end__gt&#x60;, &#x60;end__gte&#x60;, &#x60;end__lt&#x60;, &#x60;end__lte&#x60;, &#x60;name&#x60;, &#x60;space_station&#x60;, &#x60;start__gt&#x60;, &#x60;start__gte&#x60;, &#x60;start__lt&#x60;, &#x60;start__lte&#x60;  Example - [/expeditions/?space_station&#x3D;18](./?space_station&#x3D;18)  #### Search Fields searched - &#x60;crew__astronaut__agency__abbrev&#x60;, &#x60;crew__astronaut__agency__name&#x60;, &#x60;crew__astronaut__name&#x60;, &#x60;crew__astronaut__nationality__nationality_name&#x60;, &#x60;name&#x60;  Example - [/expeditions/?search&#x3D;Kelly](./?search&#x3D;Kelly)  #### Ordering Fields - &#x60;end&#x60;, &#x60;id&#x60;, &#x60;start&#x60;  Example - [/expeditions/?ordering&#x3D;-start](./?ordering&#x3D;-start)  #### Number of results Use &#x60;limit&#x60; to control the number of objects in the response (max 100)  Example - [/expeditions/?limit&#x3D;2](./?limit&#x3D;2)  #### Format Switch to JSON output - [/expeditions/?format&#x3D;json](./?format&#x3D;json)  #### Help Find all the FAQs and support links on the documentation homepage - [ll.thespacedevs.com/docs](https://ll.thespacedevs.com/docs/)
     * @param crewAstronaut  (optional)
     * @param crewAstronautAgency  (optional)
     * @param endGt End is greater than (optional)
     * @param endGte End is greater than or equal to (optional)
     * @param endLt End is less than (optional)
     * @param endLte End is greater than or equal to (optional)
     * @param limit Number of results to return per page. (optional)
     * @param name  (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param ordering Which field to use when ordering the results. (optional)
     * @param search A search term. (optional)
     * @param spaceStation  (optional)
     * @param startGt Start is greater than (optional)
     * @param startGte Start is greater than or equal to (optional)
     * @param startLt Start is less than (optional)
     * @param startLte Start is greater than or equal to (optional)
     * @return PaginatedPolymorphicExpeditionEndpointList
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun expeditionsList(crewAstronaut: kotlin.Int? = null, crewAstronautAgency: kotlin.Int? = null, endGt: kotlinx.datetime.Instant? = null, endGte: kotlinx.datetime.Instant? = null, endLt: kotlinx.datetime.Instant? = null, endLte: kotlinx.datetime.Instant? = null, limit: kotlin.Int? = null, name: kotlin.String? = null, offset: kotlin.Int? = null, ordering: kotlin.String? = null, search: kotlin.String? = null, spaceStation: kotlin.Int? = null, startGt: kotlinx.datetime.Instant? = null, startGte: kotlinx.datetime.Instant? = null, startLt: kotlinx.datetime.Instant? = null, startLte: kotlinx.datetime.Instant? = null): HttpResponse<PaginatedPolymorphicExpeditionEndpointList> {

        val localVariableAuthNames = listOf<String>("cookieAuth", "Token_Authentication")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        crewAstronaut?.apply { localVariableQuery["crew__astronaut"] = listOf("$crewAstronaut") }
        crewAstronautAgency?.apply { localVariableQuery["crew__astronaut__agency"] = listOf("$crewAstronautAgency") }
        endGt?.apply { localVariableQuery["end__gt"] = listOf("$endGt") }
        endGte?.apply { localVariableQuery["end__gte"] = listOf("$endGte") }
        endLt?.apply { localVariableQuery["end__lt"] = listOf("$endLt") }
        endLte?.apply { localVariableQuery["end__lte"] = listOf("$endLte") }
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        name?.apply { localVariableQuery["name"] = listOf("$name") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        ordering?.apply { localVariableQuery["ordering"] = listOf("$ordering") }
        search?.apply { localVariableQuery["search"] = listOf("$search") }
        spaceStation?.apply { localVariableQuery["space_station"] = listOf("$spaceStation") }
        startGt?.apply { localVariableQuery["start__gt"] = listOf("$startGt") }
        startGte?.apply { localVariableQuery["start__gte"] = listOf("$startGte") }
        startLt?.apply { localVariableQuery["start__lt"] = listOf("$startLt") }
        startLte?.apply { localVariableQuery["start__lte"] = listOf("$startLte") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/2.3.0/expeditions/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * #### Modes Levels of detail in the response - &#x60;normal&#x60;, &#x60;detailed&#x60;  Example - [/expeditions/?mode&#x3D;detailed](./?mode&#x3D;detailed)  #### Filters Parameters - &#x60;crew__astronaut&#x60;, &#x60;crew__astronaut__agency&#x60;, &#x60;end__gt&#x60;, &#x60;end__gte&#x60;, &#x60;end__lt&#x60;, &#x60;end__lte&#x60;, &#x60;name&#x60;, &#x60;space_station&#x60;, &#x60;start__gt&#x60;, &#x60;start__gte&#x60;, &#x60;start__lt&#x60;, &#x60;start__lte&#x60;  Example - [/expeditions/?space_station&#x3D;18](./?space_station&#x3D;18)  #### Search Fields searched - &#x60;crew__astronaut__agency__abbrev&#x60;, &#x60;crew__astronaut__agency__name&#x60;, &#x60;crew__astronaut__name&#x60;, &#x60;crew__astronaut__nationality__nationality_name&#x60;, &#x60;name&#x60;  Example - [/expeditions/?search&#x3D;Kelly](./?search&#x3D;Kelly)  #### Ordering Fields - &#x60;end&#x60;, &#x60;id&#x60;, &#x60;start&#x60;  Example - [/expeditions/?ordering&#x3D;-start](./?ordering&#x3D;-start)  #### Number of results Use &#x60;limit&#x60; to control the number of objects in the response (max 100)  Example - [/expeditions/?limit&#x3D;2](./?limit&#x3D;2)  #### Format Switch to JSON output - [/expeditions/?format&#x3D;json](./?format&#x3D;json)  #### Help Find all the FAQs and support links on the documentation homepage - [ll.thespacedevs.com/docs](https://ll.thespacedevs.com/docs/)
     * @param id A unique integer value identifying this expedition.
     * @return ExpeditionDetailed
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun expeditionsRetrieve(id: kotlin.Int): HttpResponse<ExpeditionDetailed> {

        val localVariableAuthNames = listOf<String>("cookieAuth", "Token_Authentication")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/2.3.0/expeditions/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


}
