/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.client.apis

import me.calebjones.spacelaunchnow.api.client.models.PaginatedPolymorphicSpacecraftFlightEndpointList
import me.calebjones.spacelaunchnow.api.client.models.SpacecraftFlightDetailed

import me.calebjones.spacelaunchnow.api.client.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class SpacecraftFlightsApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * #### Modes Levels of detail in the response - &#x60;normal&#x60;, &#x60;detailed&#x60;  Example - [/spacecraft_flights/?mode&#x3D;detailed](./?mode&#x3D;detailed)  #### Filters Parameters - &#x60;spacecraft&#x60;  Example - [/spacecraft_flights/?spacecraft&#x3D;289](./?spacecraft&#x3D;289)  #### Number of results Use &#x60;limit&#x60; to control the number of objects in the response (max 100)  Example - [/spacecraft_flights/?limit&#x3D;2](./?limit&#x3D;2)  #### Format Switch to JSON output - [/spacecraft_flights/?format&#x3D;json](./?format&#x3D;json)  #### Help Find all the FAQs and support links on the documentation homepage - [ll.thespacedevs.com/docs](https://ll.thespacedevs.com/docs/)
     * @param limit Number of results to return per page. (optional)
     * @param offset The initial index from which to return the results. (optional)
     * @param ordering Which field to use when ordering the results. (optional)
     * @param search A search term. (optional)
     * @param spacecraft  (optional)
     * @return PaginatedPolymorphicSpacecraftFlightEndpointList
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun spacecraftFlightsList(limit: kotlin.Int? = null, offset: kotlin.Int? = null, ordering: kotlin.String? = null, search: kotlin.String? = null, spacecraft: kotlin.Int? = null): HttpResponse<PaginatedPolymorphicSpacecraftFlightEndpointList> {

        val localVariableAuthNames = listOf<String>("cookieAuth", "Token_Authentication")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        ordering?.apply { localVariableQuery["ordering"] = listOf("$ordering") }
        search?.apply { localVariableQuery["search"] = listOf("$search") }
        spacecraft?.apply { localVariableQuery["spacecraft"] = listOf("$spacecraft") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/2.3.0/spacecraft_flights/",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * #### Modes Levels of detail in the response - &#x60;normal&#x60;, &#x60;detailed&#x60;  Example - [/spacecraft_flights/?mode&#x3D;detailed](./?mode&#x3D;detailed)  #### Filters Parameters - &#x60;spacecraft&#x60;  Example - [/spacecraft_flights/?spacecraft&#x3D;289](./?spacecraft&#x3D;289)  #### Number of results Use &#x60;limit&#x60; to control the number of objects in the response (max 100)  Example - [/spacecraft_flights/?limit&#x3D;2](./?limit&#x3D;2)  #### Format Switch to JSON output - [/spacecraft_flights/?format&#x3D;json](./?format&#x3D;json)  #### Help Find all the FAQs and support links on the documentation homepage - [ll.thespacedevs.com/docs](https://ll.thespacedevs.com/docs/)
     * @param id A unique integer value identifying this Spacecraft Flight.
     * @return SpacecraftFlightDetailed
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun spacecraftFlightsRetrieve(id: kotlin.Int): HttpResponse<SpacecraftFlightDetailed> {

        val localVariableAuthNames = listOf<String>("cookieAuth", "Token_Authentication")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/2.3.0/spacecraft_flights/{id}/".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


}
