package me.calebjones.spacelaunchnow.api.extensions

import kotlin.time.Instant
import me.calebjones.spacelaunchnow.api.launchlibrary.apis.LaunchesApi
import me.calebjones.spacelaunchnow.api.launchlibrary.infrastructure.HttpResponse
import me.calebjones.spacelaunchnow.api.launchlibrary.models.PaginatedLaunchBasicList
import me.calebjones.spacelaunchnow.api.launchlibrary.models.PaginatedLaunchNormalList
import kotlin.time.ExperimentalTime


/**
 * Extension functions for LaunchesApi to provide cleaner, named-parameter interfaces
 * instead of the verbose generated API methods
 */

/**
 * Get launch mini list with commonly used parameters
 */
@OptIn(ExperimentalTime::class)
suspend fun LaunchesApi.getLaunchMiniList(
    limit: Int? = null,
    upcoming: Boolean? = null,
    previous: Boolean? = null,
    ordering: String? = null,
    status: Int? = null,
    statusIds: List<Int>? = null,
    search: String? = null,
    lspId: List<Int>? = null,
    relatedLspId: List<Int>? = null,
    rocketConfigurationId: Int? = null,
    isCrewed: Boolean? = null,
    includeSuborbital: Boolean? = null,
    netGt: Instant? = null,
    netLt: Instant? = null,
    netDay: List<Double>? = null,
    netMonth: List<Double>? = null,
    pad: Int? = null,
    locationIds: List<Int>? = null
): HttpResponse<PaginatedLaunchBasicList> = launchesMiniList(
    agencyLaunchAttemptCount = null,
    agencyLaunchAttemptCountGt = null,
    agencyLaunchAttemptCountGte = null,
    agencyLaunchAttemptCountLt = null,
    agencyLaunchAttemptCountLte = null,
    agencyLaunchAttemptCountYear = null,
    agencyLaunchAttemptCountYearGt = null,
    agencyLaunchAttemptCountYearGte = null,
    agencyLaunchAttemptCountYearLt = null,
    agencyLaunchAttemptCountYearLte = null,
    id = null,
    includeSuborbital = includeSuborbital,
    isCrewed = isCrewed,
    lastUpdatedGte = null,
    lastUpdatedLte = null,
    launchDesignator = null,
    launcherConfigId = null,
    limit = limit,
    locationIds = locationIds,
    locationLaunchAttemptCount = null,
    locationLaunchAttemptCountGt = null,
    locationLaunchAttemptCountGte = null,
    locationLaunchAttemptCountLt = null,
    locationLaunchAttemptCountLte = null,
    locationLaunchAttemptCountYear = null,
    locationLaunchAttemptCountYearGt = null,
    locationLaunchAttemptCountYearGte = null,
    locationLaunchAttemptCountYearLt = null,
    locationLaunchAttemptCountYearLte = null,
    lspId = lspId,
    lspName = null,
    missionOrbitCelestialBodyId = null,
    missionOrbitName = null,
    missionOrbitNameIcontains = null,
    name = null,
    netDay = netDay,
    netGt = netGt,
    netGte = null,
    netLt = netLt,
    netLte = null,
    netMonth = netMonth,
    netYear = null,
    offset = null,
    orbitalLaunchAttemptCount = null,
    orbitalLaunchAttemptCountGt = null,
    orbitalLaunchAttemptCountGte = null,
    orbitalLaunchAttemptCountLt = null,
    orbitalLaunchAttemptCountLte = null,
    orbitalLaunchAttemptCountYear = null,
    orbitalLaunchAttemptCountYearGt = null,
    orbitalLaunchAttemptCountYearGte = null,
    orbitalLaunchAttemptCountYearLt = null,
    orbitalLaunchAttemptCountYearLte = null,
    ordering = ordering,
    pad = pad,
    padLocation = null,
    padLocationCelestialBodyId = null,
    padLaunchAttemptCount = null,
    padLaunchAttemptCountGt = null,
    padLaunchAttemptCountGte = null,
    padLaunchAttemptCountLt = null,
    padLaunchAttemptCountLte = null,
    padLaunchAttemptCountYear = null,
    padLaunchAttemptCountYearGt = null,
    padLaunchAttemptCountYearGte = null,
    padLaunchAttemptCountYearLt = null,
    padLaunchAttemptCountYearLte = null,
    previous = previous,
    program = null,
    relatedLspId = relatedLspId,
    relatedLspName = null,
    rocketConfigurationFullName = null,
    rocketConfigurationFullNameIcontains = null,
    rocketConfigurationId = rocketConfigurationId,
    rocketConfigurationManufacturerName = null,
    rocketConfigurationManufacturerNameIcontains = null,
    rocketConfigurationName = null,
    rocketSpacecraftflightSpacecraftId = null,
    rocketSpacecraftflightSpacecraftName = null,
    rocketSpacecraftflightSpacecraftNameIcontains = null,
    search = search,
    serialNumber = null,
    slug = null,
    spacecraftConfigIds = null,
    status = status,
    statusIds = statusIds,
    upcoming = upcoming,
    upcomingWithRecent = null,
    videoUrl = null,
    windowEndGt = null,
    windowEndGte = null,
    windowEndLt = null,
    windowEndLte = null,
    windowStartGt = null,
    windowStartGte = null,
    windowStartLt = null,
    windowStartLte = null
)

/**
 * Get launch normal list with commonly used parameters
 */
@OptIn(ExperimentalTime::class)
suspend fun LaunchesApi.getLaunchList(
    limit: Int? = null,
    upcoming: Boolean? = null,
    previous: Boolean? = null,
    ordering: String? = null,
    status: Int? = null,
    statusIds: List<Int>? = null,
    search: String? = null,
    lspId: List<Int>? = null,
    relatedLspId: List<Int>? = null,
    rocketConfigurationId: Int? = null,
    isCrewed: Boolean? = null,
    includeSuborbital: Boolean? = null,
    netGt: Instant? = null,
    netLt: Instant? = null,
    netDay: List<Double>? = null,
    netMonth: List<Double>? = null,
    pad: Int? = null,
    locationIds: List<Int>? = null
): HttpResponse<PaginatedLaunchNormalList> = launchesList(
    agencyLaunchAttemptCount = null,
    agencyLaunchAttemptCountGt = null,
    agencyLaunchAttemptCountGte = null,
    agencyLaunchAttemptCountLt = null,
    agencyLaunchAttemptCountLte = null,
    agencyLaunchAttemptCountYear = null,
    agencyLaunchAttemptCountYearGt = null,
    agencyLaunchAttemptCountYearGte = null,
    agencyLaunchAttemptCountYearLt = null,
    agencyLaunchAttemptCountYearLte = null,
    id = null,
    includeSuborbital = includeSuborbital,
    isCrewed = isCrewed,
    lastUpdatedGte = null,
    lastUpdatedLte = null,
    launchDesignator = null,
    launcherConfigId = null,
    limit = limit,
    locationIds = locationIds,
    locationLaunchAttemptCount = null,
    locationLaunchAttemptCountGt = null,
    locationLaunchAttemptCountGte = null,
    locationLaunchAttemptCountLt = null,
    locationLaunchAttemptCountLte = null,
    locationLaunchAttemptCountYear = null,
    locationLaunchAttemptCountYearGt = null,
    locationLaunchAttemptCountYearGte = null,
    locationLaunchAttemptCountYearLt = null,
    locationLaunchAttemptCountYearLte = null,
    lspId = lspId,
    lspName = null,
    missionOrbitCelestialBodyId = null,
    missionOrbitName = null,
    missionOrbitNameIcontains = null,
    name = null,
    netDay = netDay,
    netGt = netGt,
    netGte = null,
    netLt = netLt,
    netLte = null,
    netMonth = netMonth,
    netYear = null,
    offset = null,
    orbitalLaunchAttemptCount = null,
    orbitalLaunchAttemptCountGt = null,
    orbitalLaunchAttemptCountGte = null,
    orbitalLaunchAttemptCountLt = null,
    orbitalLaunchAttemptCountLte = null,
    orbitalLaunchAttemptCountYear = null,
    orbitalLaunchAttemptCountYearGt = null,
    orbitalLaunchAttemptCountYearGte = null,
    orbitalLaunchAttemptCountYearLt = null,
    orbitalLaunchAttemptCountYearLte = null,
    ordering = ordering,
    pad = pad,
    padLocation = null,
    padLocationCelestialBodyId = null,
    padLaunchAttemptCount = null,
    padLaunchAttemptCountGt = null,
    padLaunchAttemptCountGte = null,
    padLaunchAttemptCountLt = null,
    padLaunchAttemptCountLte = null,
    padLaunchAttemptCountYear = null,
    padLaunchAttemptCountYearGt = null,
    padLaunchAttemptCountYearGte = null,
    padLaunchAttemptCountYearLt = null,
    padLaunchAttemptCountYearLte = null,
    previous = previous,
    program = null,
    relatedLspId = null,
    relatedLspName = null,
    rocketConfigurationFullName = null,
    rocketConfigurationFullNameIcontains = null,
    rocketConfigurationId = rocketConfigurationId,
    rocketConfigurationManufacturerName = null,
    rocketConfigurationManufacturerNameIcontains = null,
    rocketConfigurationName = null,
    rocketSpacecraftflightSpacecraftId = null,
    rocketSpacecraftflightSpacecraftName = null,
    rocketSpacecraftflightSpacecraftNameIcontains = null,
    search = search,
    serialNumber = null,
    slug = null,
    spacecraftConfigIds = null,
    status = status,
    statusIds = statusIds,
    upcoming = upcoming,
    upcomingWithRecent = null,
    videoUrl = null,
    windowEndGt = null,
    windowEndGte = null,
    windowEndLt = null,
    windowEndLte = null,
    windowStartGt = null,
    windowStartGte = null,
    windowStartLt = null,
    windowStartLte = null
)
