/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import me.calebjones.spacelaunchnow.api.launchlibrary.models.AgencyMini
import me.calebjones.spacelaunchnow.api.launchlibrary.models.AstronautStatus
import me.calebjones.spacelaunchnow.api.launchlibrary.models.AstronautType
import me.calebjones.spacelaunchnow.api.launchlibrary.models.Country
import me.calebjones.spacelaunchnow.api.launchlibrary.models.Image
import me.calebjones.spacelaunchnow.api.launchlibrary.models.LaunchBasic
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SocialMediaLink
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpacecraftFlightNormal
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpacewalkNormal

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param url 
 * @param responseMode 
 * @param name 
 * @param status 
 * @param agency 
 * @param image 
 * @param age 
 * @param bio 
 * @param type 
 * @param nationality 
 * @param inSpace 
 * @param timeInSpace 
 * @param evaTime 
 * @param dateOfBirth 
 * @param dateOfDeath 
 * @param wiki 
 * @param lastFlight 
 * @param firstFlight 
 * @param socialMediaLinks 
 * @param flightsCount 
 * @param landingsCount 
 * @param spacewalksCount 
 * @param flights 
 * @param landings 
 * @param spacewalks 
 */
@Serializable

data class AstronautEndpointDetailed (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "detailed",

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "status") @Required val status: AstronautStatus?,

    @SerialName(value = "agency") @Required val agency: AgencyMini?,

    @SerialName(value = "image") @Required val image: Image?,

    @SerialName(value = "age") @Required val age: kotlin.Int?,

    @SerialName(value = "bio") @Required val bio: kotlin.String,

    @SerialName(value = "type") @Required val type: AstronautType,

    @SerialName(value = "nationality") @Required val nationality: kotlin.collections.List<Country>,

    @SerialName(value = "in_space") @Required val inSpace: kotlin.Boolean?,

    @SerialName(value = "time_in_space") @Required val timeInSpace: kotlin.String?,

    @SerialName(value = "eva_time") @Required val evaTime: kotlin.String?,

    @SerialName(value = "date_of_birth") @Required val dateOfBirth: kotlinx.datetime.LocalDate?,

    @SerialName(value = "date_of_death") @Required val dateOfDeath: kotlinx.datetime.LocalDate?,

    @SerialName(value = "wiki") @Required val wiki: kotlin.String?,

    @SerialName(value = "last_flight") @Required val lastFlight: kotlinx.datetime.Instant?,

    @SerialName(value = "first_flight") @Required val firstFlight: kotlinx.datetime.Instant?,

    @SerialName(value = "social_media_links") @Required val socialMediaLinks: kotlin.collections.List<SocialMediaLink>?,

    @SerialName(value = "flights_count") @Required val flightsCount: kotlin.Int?,

    @SerialName(value = "landings_count") @Required val landingsCount: kotlin.Int?,

    @SerialName(value = "spacewalks_count") @Required val spacewalksCount: kotlin.Int?,

    @SerialName(value = "flights") @Required val flights: kotlin.collections.List<LaunchBasic>,

    @SerialName(value = "landings") @Required val landings: kotlin.collections.List<SpacecraftFlightNormal>,

    @SerialName(value = "spacewalks") @Required val spacewalks: kotlin.collections.List<SpacewalkNormal>

) {


}

