/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import me.calebjones.spacelaunchnow.api.launchlibrary.models.AgencyMini
import me.calebjones.spacelaunchnow.api.launchlibrary.models.AstronautStatus
import me.calebjones.spacelaunchnow.api.launchlibrary.models.AstronautType
import me.calebjones.spacelaunchnow.api.launchlibrary.models.Country
import me.calebjones.spacelaunchnow.api.launchlibrary.models.Image

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param url 
 * @param responseMode 
 * @param name 
 * @param status 
 * @param agency 
 * @param image 
 * @param age 
 * @param bio 
 * @param type 
 * @param nationality 
 */
@Serializable

data class AstronautNormal (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "normal",

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "status") @Required val status: AstronautStatus?,

    @SerialName(value = "agency") @Required val agency: AgencyMini?,

    @SerialName(value = "image") @Required val image: Image?,

    @SerialName(value = "age") @Required val age: kotlin.Int?,

    @SerialName(value = "bio") @Required val bio: kotlin.String,

    @SerialName(value = "type") @Required val type: AstronautType,

    @SerialName(value = "nationality") @Required val nationality: kotlin.collections.List<Country>

) {


}

