/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import me.calebjones.spacelaunchnow.api.launchlibrary.models.PayloadMini
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpaceStationMini
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpacecraftConfigNormal

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param spacestation 
 * @param spacecraft 
 * @param payload 
 */
@Serializable

data class DockingLocation (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "spacestation") @Required val spacestation: SpaceStationMini?,

    @SerialName(value = "spacecraft") @Required val spacecraft: SpacecraftConfigNormal?,

    @SerialName(value = "payload") @Required val payload: PayloadMini?

) {


}

