/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import me.calebjones.spacelaunchnow.api.launchlibrary.models.ImageLicense
import me.calebjones.spacelaunchnow.api.launchlibrary.models.ImageVariant

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param imageUrl 
 * @param thumbnailUrl 
 * @param credit 
 * @param license 
 * @param variants 
 * @param singleUse 
 */
@Serializable

data class Image (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "image_url") @Required val imageUrl: kotlin.String,

    @SerialName(value = "thumbnail_url") @Required val thumbnailUrl: kotlin.String,

    @SerialName(value = "credit") @Required val credit: kotlin.String?,

    @SerialName(value = "license") @Required val license: ImageLicense,

    @SerialName(value = "variants") @Required val variants: kotlin.collections.List<ImageVariant>,

    @SerialName(value = "single_use") val singleUse: kotlin.Boolean? = null

) {


}

