/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import me.calebjones.spacelaunchnow.api.launchlibrary.models.AgencyMini
import me.calebjones.spacelaunchnow.api.launchlibrary.models.Image
import me.calebjones.spacelaunchnow.api.launchlibrary.models.LaunchStatus
import me.calebjones.spacelaunchnow.api.launchlibrary.models.NetPrecision

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param url 
 * @param responseMode 
 * @param slug 
 * @param launchDesignator 
 * @param status 
 * @param netPrecision 
 * @param image 
 * @param launchServiceProvider 
 * @param infographic 
 * @param locationName 
 * @param name 
 * @param lastUpdated 
 * @param net 
 * @param windowEnd 
 * @param windowStart 
 */
@Serializable

data class LaunchBasic (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "list",

    @SerialName(value = "slug") @Required val slug: kotlin.String,

    @SerialName(value = "launch_designator") @Required val launchDesignator: kotlin.String?,

    @SerialName(value = "status") @Required val status: LaunchStatus?,

    @SerialName(value = "net_precision") @Required val netPrecision: NetPrecision?,

    @SerialName(value = "image") @Required val image: Image?,

    @SerialName(value = "launch_service_provider") @Required val launchServiceProvider: AgencyMini,

    @SerialName(value = "infographic") @Required val infographic: kotlin.String?,

    @SerialName(value = "location_name") @Required val locationName: kotlin.String?,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "last_updated") val lastUpdated: kotlin.time.Instant? = null,

    @SerialName(value = "net") val net: kotlin.time.Instant? = null,

    @SerialName(value = "window_end") val windowEnd: kotlin.time.Instant? = null,

    @SerialName(value = "window_start") val windowStart: kotlin.time.Instant? = null

) {


}

