/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import me.calebjones.spacelaunchnow.api.launchlibrary.models.LaunchNormal
import me.calebjones.spacelaunchnow.api.launchlibrary.models.PayloadNormal

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param responseMode 
 * @param id 
 * @param url 
 * @param destination 
 * @param payload 
 * @param launch 
 * @param amount 
 */
@Serializable

data class PayloadFlightNormalSerializerNoLanding (

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "normal",

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "destination") @Required val destination: kotlin.String?,

    @SerialName(value = "payload") @Required val payload: PayloadNormal,

    @SerialName(value = "launch") @Required val launch: LaunchNormal,

    @SerialName(value = "amount") val amount: kotlin.Int? = null

) {


}

