/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import me.calebjones.spacelaunchnow.api.launchlibrary.models.FirstStageNormal
import me.calebjones.spacelaunchnow.api.launchlibrary.models.LauncherConfigDetailed
import me.calebjones.spacelaunchnow.api.launchlibrary.models.PayloadFlightDetailed
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpacecraftFlightDetailed

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param responseMode 
 * @param id 
 * @param url 
 * @param configuration 
 * @param launcherStage 
 * @param spacecraftStage 
 * @param payloads 
 */
@Serializable

data class RocketStandaloneDetailed (

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "detailed",

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "configuration") @Required val configuration: LauncherConfigDetailed,

    @SerialName(value = "launcher_stage") @Required val launcherStage: kotlin.collections.List<FirstStageNormal>,

    @SerialName(value = "spacecraft_stage") @Required val spacecraftStage: kotlin.collections.List<SpacecraftFlightDetailed>,

    @SerialName(value = "payloads") @Required val payloads: kotlin.collections.List<PayloadFlightDetailed>

) {


}

