/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import me.calebjones.spacelaunchnow.api.launchlibrary.models.SocialMedia

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param socialMedia 
 * @param url 
 */
@Serializable

data class SocialMediaLink (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "social_media") @Required val socialMedia: SocialMedia,

    @SerialName(value = "url") @Required val url: kotlin.String?

) {


}

