/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import me.calebjones.spacelaunchnow.api.launchlibrary.models.LaunchNormal
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpacecraftNormal

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param url 
 * @param destination 
 * @param missionEnd 
 * @param spacecraft 
 * @param launch 
 * @param duration 
 * @param turnAroundTime 
 * @param responseMode 
 */
@Serializable

data class SpacecraftFlightNormalSerializerNoLanding (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "destination") @Required val destination: kotlin.String?,

    @SerialName(value = "mission_end") @Required val missionEnd: kotlinx.datetime.Instant?,

    @SerialName(value = "spacecraft") @Required val spacecraft: SpacecraftNormal,

    @SerialName(value = "launch") @Required val launch: LaunchNormal,

    @SerialName(value = "duration") @Required val duration: kotlin.String?,

    @SerialName(value = "turn_around_time") @Required val turnAroundTime: kotlin.String?,

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "normal"

) {


}

