/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import me.calebjones.spacelaunchnow.api.launchlibrary.models.AgencyNormal
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpacecraftConfigFamilyNormal

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param responseMode 
 * @param id 
 * @param name 
 * @param manufacturer 
 * @param parent 
 * @param maidenFlight 
 * @param spacecraftFlown 
 * @param totalLaunchCount 
 * @param successfulLaunches 
 * @param failedLaunches 
 * @param attemptedLandings 
 * @param successfulLandings 
 * @param failedLandings 
 * @param description 
 */
@Serializable

data class SpacecraftConfigFamilyDetailed (

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "normal",

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "manufacturer") @Required val manufacturer: AgencyNormal?,

    @SerialName(value = "parent") @Required val parent: SpacecraftConfigFamilyNormal?,

    @SerialName(value = "maiden_flight") @Required val maidenFlight: kotlinx.datetime.LocalDate?,

    @SerialName(value = "spacecraft_flown") @Required val spacecraftFlown: kotlin.Int?,

    @SerialName(value = "total_launch_count") @Required val totalLaunchCount: kotlin.Int?,

    @SerialName(value = "successful_launches") @Required val successfulLaunches: kotlin.Int?,

    @SerialName(value = "failed_launches") @Required val failedLaunches: kotlin.Int?,

    @SerialName(value = "attempted_landings") @Required val attemptedLandings: kotlin.Int?,

    @SerialName(value = "successful_landings") @Required val successfulLandings: kotlin.Int?,

    @SerialName(value = "failed_landings") @Required val failedLandings: kotlin.Int?,

    @SerialName(value = "description") val description: kotlin.String? = null

) {


}

