/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Compact shape for list endpoints.
 *
 * @param id 
 * @param name 
 * @param slug 
 * @param type 
 * @param typeId 
 * @param date 
 * @param imageUrl 
 * @param location 
 * @param webcastLive 
 * @param programIds 
 * @param launchIds 
 */
@Serializable

data class EventList (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "slug") val slug: kotlin.String? = null,

    @SerialName(value = "type") val type: kotlin.String? = null,

    @SerialName(value = "type_id") val typeId: kotlin.Int? = null,

    @SerialName(value = "date") val date: kotlin.time.Instant? = null,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null,

    @SerialName(value = "location") val location: kotlin.String? = null,

    @SerialName(value = "webcast_live") val webcastLive: kotlin.Boolean? = false,

    @SerialName(value = "program_ids") val programIds: kotlin.collections.List<kotlin.Int>? = null,

    @SerialName(value = "launch_ids") val launchIds: kotlin.collections.List<kotlin.String>? = null

) {


}

