/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models

import me.calebjones.spacelaunchnow.api.trantor.models.ExpeditionCrewMember

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param start 
 * @param end 
 * @param crew 
 */
@Serializable

data class Expedition (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "start") val start: kotlin.time.Instant? = null,

    @SerialName(value = "end") val end: kotlin.time.Instant? = null,

    @SerialName(value = "crew") val crew: kotlin.collections.List<ExpeditionCrewMember>? = null

) {


}

