/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param attempt 
 * @param description 
 * @param landingLocationName 
 * @param success 
 * @param type 
 */
@Serializable

data class LandingSummary (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "attempt") val attempt: kotlin.Boolean? = false,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "landing_location_name") val landingLocationName: kotlin.String? = null,

    @SerialName(value = "success") val success: kotlin.Boolean? = null,

    @SerialName(value = "type") val type: kotlin.String? = null

) {


}

