/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param comment 
 * @param createdOn 
 * @param infoUrl 
 * @param createdBy 
 */
@Serializable

data class LaunchUpdate (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "comment") @Required val comment: kotlin.String,

    @SerialName(value = "created_on") @Required val createdOn: kotlin.time.Instant,

    @SerialName(value = "info_url") val infoUrl: kotlin.String? = null,

    @SerialName(value = "created_by") val createdBy: kotlin.String? = null

) {


}

