/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param fullName 
 * @param variant 
 * @param active 
 * @param reusable 
 * @param manufacturerId 
 * @param imageUrl 
 * @param infoUrl 
 * @param wikiUrl 
 */
@Serializable

data class LauncherConfigSummary (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "full_name") val fullName: kotlin.String? = null,

    @SerialName(value = "variant") val variant: kotlin.String? = null,

    @SerialName(value = "active") val active: kotlin.Boolean? = true,

    @SerialName(value = "reusable") val reusable: kotlin.Boolean? = false,

    @SerialName(value = "manufacturer_id") val manufacturerId: kotlin.Int? = null,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null,

    @SerialName(value = "info_url") val infoUrl: kotlin.String? = null,

    @SerialName(value = "wiki_url") val wikiUrl: kotlin.String? = null

) {


}

