/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models

import me.calebjones.spacelaunchnow.api.trantor.models.AgencySummary
import me.calebjones.spacelaunchnow.api.trantor.models.InfoUrl
import me.calebjones.spacelaunchnow.api.trantor.models.LaunchUpdate
import me.calebjones.spacelaunchnow.api.trantor.models.Mission
import me.calebjones.spacelaunchnow.api.trantor.models.MissionPatchSchema
import me.calebjones.spacelaunchnow.api.trantor.models.PadSummary
import me.calebjones.spacelaunchnow.api.trantor.models.Rocket
import me.calebjones.spacelaunchnow.api.trantor.models.TimelineEvent
import me.calebjones.spacelaunchnow.api.trantor.models.VidUrl

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Default detail response — FK IDs + denormalized names.
 *
 * @param id 
 * @param name 
 * @param net 
 * @param slug 
 * @param status 
 * @param statusId 
 * @param agencyLaunchAttemptCount 
 * @param agencyLaunchAttemptCountYear 
 * @param failreason 
 * @param flightclubUrl 
 * @param imageUrl 
 * @param infoUrls 
 * @param lastUpdated 
 * @param locationLaunchAttemptCount 
 * @param locationLaunchAttemptCountYear 
 * @param mission 
 * @param missionId 
 * @param missionPatches 
 * @param netPrecision 
 * @param netPrecisionId 
 * @param orbitalLaunchAttemptCount 
 * @param orbitalLaunchAttemptCountYear 
 * @param pad 
 * @param padId 
 * @param padLaunchAttemptCount 
 * @param padLaunchAttemptCountYear 
 * @param padTurnaround 
 * @param probability 
 * @param provider 
 * @param providerId 
 * @param providerName 
 * @param rocket 
 * @param rocketId 
 * @param timeline 
 * @param updates 
 * @param vidUrls 
 * @param weatherConcerns 
 * @param webcastLive 
 * @param windowEnd 
 * @param windowStart 
 */
@Serializable

data class LaunchDetail (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "net") @Required val net: kotlin.time.Instant,

    @SerialName(value = "slug") @Required val slug: kotlin.String,

    @SerialName(value = "status") @Required val status: kotlin.String,

    @SerialName(value = "status_id") @Required val statusId: kotlin.Int,

    @SerialName(value = "agency_launch_attempt_count") val agencyLaunchAttemptCount: kotlin.Int? = null,

    @SerialName(value = "agency_launch_attempt_count_year") val agencyLaunchAttemptCountYear: kotlin.Int? = null,

    @SerialName(value = "failreason") val failreason: kotlin.String? = null,

    @SerialName(value = "flightclub_url") val flightclubUrl: kotlin.String? = null,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null,

    @SerialName(value = "info_urls") val infoUrls: kotlin.collections.List<InfoUrl>? = null,

    @SerialName(value = "last_updated") val lastUpdated: kotlin.time.Instant? = null,

    @SerialName(value = "location_launch_attempt_count") val locationLaunchAttemptCount: kotlin.Int? = null,

    @SerialName(value = "location_launch_attempt_count_year") val locationLaunchAttemptCountYear: kotlin.Int? = null,

    @SerialName(value = "mission") val mission: Mission? = null,

    @SerialName(value = "mission_id") val missionId: kotlin.Int? = null,

    @SerialName(value = "mission_patches") val missionPatches: kotlin.collections.List<MissionPatchSchema>? = null,

    @SerialName(value = "net_precision") val netPrecision: kotlin.String? = null,

    @SerialName(value = "net_precision_id") val netPrecisionId: kotlin.Int? = null,

    @SerialName(value = "orbital_launch_attempt_count") val orbitalLaunchAttemptCount: kotlin.Int? = null,

    @SerialName(value = "orbital_launch_attempt_count_year") val orbitalLaunchAttemptCountYear: kotlin.Int? = null,

    @SerialName(value = "pad") val pad: PadSummary? = null,

    @SerialName(value = "pad_id") val padId: kotlin.Int? = null,

    @SerialName(value = "pad_launch_attempt_count") val padLaunchAttemptCount: kotlin.Int? = null,

    @SerialName(value = "pad_launch_attempt_count_year") val padLaunchAttemptCountYear: kotlin.Int? = null,

    @SerialName(value = "pad_turnaround") val padTurnaround: kotlin.String? = null,

    @SerialName(value = "probability") val probability: kotlin.Int? = null,

    @SerialName(value = "provider") val provider: AgencySummary? = null,

    @SerialName(value = "provider_id") val providerId: kotlin.Int? = null,

    @SerialName(value = "provider_name") val providerName: kotlin.String? = null,

    @SerialName(value = "rocket") val rocket: Rocket? = null,

    @SerialName(value = "rocket_id") val rocketId: kotlin.Int? = null,

    @SerialName(value = "timeline") val timeline: kotlin.collections.List<TimelineEvent>? = null,

    @SerialName(value = "updates") val updates: kotlin.collections.List<LaunchUpdate>? = null,

    @SerialName(value = "vid_urls") val vidUrls: kotlin.collections.List<VidUrl>? = null,

    @SerialName(value = "weather_concerns") val weatherConcerns: kotlin.String? = null,

    @SerialName(value = "webcast_live") val webcastLive: kotlin.Boolean? = false,

    @SerialName(value = "window_end") val windowEnd: kotlin.time.Instant? = null,

    @SerialName(value = "window_start") val windowStart: kotlin.time.Instant? = null

) {


}

