/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param serialNumber 
 * @param attemptedLandings 
 * @param details 
 * @param flightProven 
 * @param flights 
 * @param status 
 * @param successfulLandings 
 */
@Serializable

data class LauncherSummary (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "serial_number") @Required val serialNumber: kotlin.String,

    @SerialName(value = "attempted_landings") val attemptedLandings: kotlin.Int? = 0,

    @SerialName(value = "details") val details: kotlin.String? = null,

    @SerialName(value = "flight_proven") val flightProven: kotlin.Boolean? = false,

    @SerialName(value = "flights") val flights: kotlin.Int? = 0,

    @SerialName(value = "status") val status: kotlin.String? = null,

    @SerialName(value = "successful_landings") val successfulLandings: kotlin.Int? = 0

) {


}

