/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param latitude 
 * @param longitude 
 * @param location 
 * @param locationId 
 * @param totalLaunchCount 
 * @param imageUrl 
 */
@Serializable

data class PadSummary (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "latitude") @Required val latitude: kotlin.Double,

    @SerialName(value = "longitude") @Required val longitude: kotlin.Double,

    @SerialName(value = "location") val location: kotlin.String? = null,

    @SerialName(value = "location_id") val locationId: kotlin.Int? = null,

    @SerialName(value = "total_launch_count") val totalLaunchCount: kotlin.Int? = 0,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null

) {


}

