/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * List row + description and external links.
 *
 * @param id 
 * @param name 
 * @param agencyIds 
 * @param description 
 * @param endDate 
 * @param imageUrl 
 * @param infoUrl 
 * @param startDate 
 * @param wikiUrl 
 */
@Serializable

data class ProgramDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "agency_ids") val agencyIds: kotlin.collections.List<kotlin.Int>? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "end_date") val endDate: kotlin.time.Instant? = null,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null,

    @SerialName(value = "info_url") val infoUrl: kotlin.String? = null,

    @SerialName(value = "start_date") val startDate: kotlin.time.Instant? = null,

    @SerialName(value = "wiki_url") val wikiUrl: kotlin.String? = null

) {


}

