/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models

import me.calebjones.spacelaunchnow.api.trantor.models.StageSummary

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param configurationId 
 * @param configurationName 
 * @param stages 
 */
@Serializable

data class RocketSummary (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "configuration_id") @Required val configurationId: kotlin.Int,

    @SerialName(value = "configuration_name") val configurationName: kotlin.String? = null,

    @SerialName(value = "stages") val stages: kotlin.collections.List<StageSummary>? = null

) {


}

