/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Lean row for ``GET /spacecraft_configurations``.
 *
 * @param id 
 * @param name 
 * @param type 
 * @param agencyId 
 * @param agencyName 
 * @param inUse 
 * @param humanRated 
 * @param imageUrl 
 * @param infoUrl 
 * @param wikiUrl 
 */
@Serializable

data class SpacecraftConfigSummary (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "type") val type: kotlin.String? = null,

    @SerialName(value = "agency_id") val agencyId: kotlin.Int? = null,

    @SerialName(value = "agency_name") val agencyName: kotlin.String? = null,

    @SerialName(value = "in_use") val inUse: kotlin.Boolean? = null,

    @SerialName(value = "human_rated") val humanRated: kotlin.Boolean? = null,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null,

    @SerialName(value = "info_url") val infoUrl: kotlin.String? = null,

    @SerialName(value = "wiki_url") val wikiUrl: kotlin.String? = null

) {


}

