/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Compact shape for list endpoints.
 *
 * @param id 
 * @param name 
 * @param status 
 * @param statusId 
 * @param type 
 * @param typeId 
 * @param imageUrl 
 * @param orbit 
 * @param founded 
 * @param deorbited 
 */
@Serializable

data class StationList (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "status") val status: kotlin.String? = null,

    @SerialName(value = "status_id") val statusId: kotlin.Int? = null,

    @SerialName(value = "type") val type: kotlin.String? = null,

    @SerialName(value = "type_id") val typeId: kotlin.Int? = null,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null,

    @SerialName(value = "orbit") val orbit: kotlin.String? = null,

    @SerialName(value = "founded") val founded: kotlinx.datetime.LocalDate? = null,

    @SerialName(value = "deorbited") val deorbited: kotlin.Boolean? = null

) {


}

