/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models

import me.calebjones.spacelaunchnow.api.trantor.models.AgencyList
import me.calebjones.spacelaunchnow.api.trantor.models.Expedition

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * List row + description, physical measurements, owners, expeditions.
 *
 * @param id 
 * @param name 
 * @param deorbited 
 * @param description 
 * @param dockedVehicles 
 * @param expeditions 
 * @param founded 
 * @param height 
 * @param imageUrl 
 * @param mass 
 * @param onboardCrew 
 * @param orbit 
 * @param ownerIds Deprecated — use owners[]; removed one release after the client pass (E12(P5)).
 * @param ownerNames Deprecated — use owners[]; removed one release after the client pass (E12(P5)).
 * @param owners 
 * @param status 
 * @param statusId 
 * @param type 
 * @param typeId 
 * @param volume 
 * @param width 
 */
@Serializable

data class StationDetail (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "deorbited") val deorbited: kotlin.Boolean? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "docked_vehicles") val dockedVehicles: kotlin.Int? = null,

    @SerialName(value = "expeditions") val expeditions: kotlin.collections.List<Expedition>? = null,

    @SerialName(value = "founded") val founded: kotlinx.datetime.LocalDate? = null,

    @SerialName(value = "height") val height: kotlin.Double? = null,

    @SerialName(value = "image_url") val imageUrl: kotlin.String? = null,

    @SerialName(value = "mass") val mass: kotlin.Double? = null,

    @SerialName(value = "onboard_crew") val onboardCrew: kotlin.Int? = null,

    @SerialName(value = "orbit") val orbit: kotlin.String? = null,

    /* Deprecated — use owners[]; removed one release after the client pass (E12(P5)). */
    @SerialName(value = "owner_ids") val ownerIds: kotlin.collections.List<kotlin.Int>? = null,

    /* Deprecated — use owners[]; removed one release after the client pass (E12(P5)). */
    @SerialName(value = "owner_names") val ownerNames: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "owners") val owners: kotlin.collections.List<AgencyList>? = null,

    @SerialName(value = "status") val status: kotlin.String? = null,

    @SerialName(value = "status_id") val statusId: kotlin.Int? = null,

    @SerialName(value = "type") val type: kotlin.String? = null,

    @SerialName(value = "type_id") val typeId: kotlin.Int? = null,

    @SerialName(value = "volume") val volume: kotlin.Int? = null,

    @SerialName(value = "width") val width: kotlin.Double? = null

) {


}

