/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Flat row for the standalone updates feed.
 *
 * @param id 
 * @param comment 
 * @param infoUrl 
 * @param createdBy 
 * @param createdOn 
 * @param launchId 
 * @param launchName 
 * @param eventId 
 * @param eventName 
 * @param programId 
 * @param profileImage 
 */
@Serializable

data class UpdateList (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "comment") val comment: kotlin.String? = null,

    @SerialName(value = "info_url") val infoUrl: kotlin.String? = null,

    @SerialName(value = "created_by") val createdBy: kotlin.String? = null,

    @SerialName(value = "created_on") val createdOn: kotlin.time.Instant? = null,

    @SerialName(value = "launch_id") val launchId: kotlin.String? = null,

    @SerialName(value = "launch_name") val launchName: kotlin.String? = null,

    @SerialName(value = "event_id") val eventId: kotlin.Int? = null,

    @SerialName(value = "event_name") val eventName: kotlin.String? = null,

    @SerialName(value = "program_id") val programId: kotlin.Int? = null,

    @SerialName(value = "profile_image") val profileImage: kotlin.String? = null

) {


}

