/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.snapi.models

import me.calebjones.spacelaunchnow.api.snapi.models.Author

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param title 
 * @param authors 
 * @param url 
 * @param imageUrl 
 * @param newsSite 
 * @param publishedAt 
 * @param updatedAt 
 * @param summary 
 */
@Serializable

data class Report (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "authors") @Required val authors: kotlin.collections.List<Author>,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "image_url") @Required val imageUrl: kotlin.String,

    @SerialName(value = "news_site") @Required val newsSite: kotlin.String,

    @SerialName(value = "published_at") @Required val publishedAt: kotlinx.datetime.Instant,

    @SerialName(value = "updated_at") @Required val updatedAt: kotlinx.datetime.Instant,

    @SerialName(value = "summary") val summary: kotlin.String? = null

) {


}

