/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import me.calebjones.spacelaunchnow.api.models.EventType
import me.calebjones.spacelaunchnow.api.models.Image
import me.calebjones.spacelaunchnow.api.models.InfoURL
import me.calebjones.spacelaunchnow.api.models.NetPrecision
import me.calebjones.spacelaunchnow.api.models.VidURL

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param url 
 * @param name 
 * @param infoUrls 
 * @param vidUrls 
 * @param image 
 * @param slug 
 * @param type 
 * @param datePrecision 
 * @param date 
 * @param description 
 * @param webcastLive 
 * @param location 
 */
@Serializable

data class EventNormal (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "info_urls") @Required val infoUrls: kotlin.collections.List<InfoURL>,

    @SerialName(value = "vid_urls") @Required val vidUrls: kotlin.collections.List<VidURL>,

    @SerialName(value = "image") @Required val image: Image?,

    @SerialName(value = "slug") @Required val slug: kotlin.String,

    @SerialName(value = "type") @Required val type: EventType,

    @SerialName(value = "date_precision") @Required val datePrecision: NetPrecision?,

    @SerialName(value = "date") val date: kotlinx.datetime.Instant? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "webcast_live") val webcastLive: kotlin.Boolean? = null,

    @SerialName(value = "location") val location: kotlin.String? = null

) {


}

