/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import me.calebjones.spacelaunchnow.api.models.MissionPatch
import me.calebjones.spacelaunchnow.api.models.SpaceStationNormal

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param url 
 * @param name 
 * @param start 
 * @param end 
 * @param spacestation 
 * @param missionPatches 
 */
@Serializable

data class ExpeditionNormalSerializerForSpacewalk (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String?,

    @SerialName(value = "start") @Required val start: kotlinx.datetime.Instant?,

    @SerialName(value = "end") @Required val end: kotlinx.datetime.Instant?,

    @SerialName(value = "spacestation") @Required val spacestation: SpaceStationNormal,

    @SerialName(value = "mission_patches") @Required val missionPatches: kotlin.collections.List<MissionPatch>

) {


}

