/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import me.calebjones.spacelaunchnow.api.models.EventEndpointList
import me.calebjones.spacelaunchnow.api.models.LaunchBasic

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param launches 
 * @param events 
 */
@Serializable

data class LaunchAndEventsList (

    @SerialName(value = "launches") @Required val launches: kotlin.collections.List<LaunchBasic>,

    @SerialName(value = "events") @Required val events: kotlin.collections.List<EventEndpointList>

) {


}

