/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import me.calebjones.spacelaunchnow.api.models.LauncherConfigFamilyMini

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param responseMode 
 * @param id 
 * @param url 
 * @param name 
 * @param families 
 * @param fullName 
 * @param variant 
 */
@Serializable

data class LauncherConfigList (

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "list",

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "families") @Required val families: kotlin.collections.List<LauncherConfigFamilyMini>?,

    @SerialName(value = "full_name") val fullName: kotlin.String? = null,

    @SerialName(value = "variant") val variant: kotlin.String? = null

) {


}

