/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import me.calebjones.spacelaunchnow.api.models.AgencyDetailed
import me.calebjones.spacelaunchnow.api.models.ExpeditionNormal
import me.calebjones.spacelaunchnow.api.models.LaunchNormal
import me.calebjones.spacelaunchnow.api.models.ProgramNormal

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param imageUrl 
 * @param agency 
 * @param responseMode 
 * @param launches 
 * @param expeditions 
 * @param program 
 * @param priority 
 */
@Serializable

data class MissionPatchDetailed (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "image_url") @Required val imageUrl: kotlin.String,

    @SerialName(value = "agency") @Required val agency: AgencyDetailed?,

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "detailed",

    @SerialName(value = "launches") @Required val launches: kotlin.collections.List<LaunchNormal>,

    @SerialName(value = "expeditions") @Required val expeditions: kotlin.collections.List<ExpeditionNormal>,

    @SerialName(value = "program") @Required val program: kotlin.collections.List<ProgramNormal>,

    @SerialName(value = "priority") val priority: kotlin.Int? = null

) {


}

