/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import me.calebjones.spacelaunchnow.api.models.LandingEndpointDetailed

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param count 
 * @param results 
 * @param next 
 * @param previous 
 */
@Serializable

data class PaginatedLandingEndpointDetailedList (

    @SerialName(value = "count") @Required val count: kotlin.Int,

    @SerialName(value = "results") @Required val results: kotlin.collections.List<LandingEndpointDetailed>,

    @SerialName(value = "next") val next: kotlin.String? = null,

    @SerialName(value = "previous") val previous: kotlin.String? = null

) {


}

