/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import me.calebjones.spacelaunchnow.api.models.LaunchAndEventsList
import me.calebjones.spacelaunchnow.api.models.LauncherDetailed
import me.calebjones.spacelaunchnow.api.models.Notice
import me.calebjones.spacelaunchnow.api.models.RoadClosure
import me.calebjones.spacelaunchnow.api.models.SpacecraftNormal
import me.calebjones.spacelaunchnow.api.models.Update
import me.calebjones.spacelaunchnow.api.models.VidURLs

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param responseMode 
 * @param updates 
 * @param liveStreams 
 * @param roadClosures 
 * @param notices 
 * @param vehicles 
 * @param orbiters 
 * @param upcoming 
 * @param previous 
 */
@Serializable

data class StarshipDashboardList (

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "list",

    @SerialName(value = "updates") @Required val updates: kotlin.collections.List<Update>,

    @SerialName(value = "live_streams") @Required val liveStreams: kotlin.collections.List<VidURLs>,

    @SerialName(value = "road_closures") @Required val roadClosures: kotlin.collections.List<RoadClosure>,

    @SerialName(value = "notices") @Required val notices: kotlin.collections.List<Notice>,

    @SerialName(value = "vehicles") @Required val vehicles: kotlin.collections.List<LauncherDetailed>,

    @SerialName(value = "orbiters") @Required val orbiters: kotlin.collections.List<SpacecraftNormal>,

    @SerialName(value = "upcoming") @Required val upcoming: LaunchAndEventsList,

    @SerialName(value = "previous") @Required val previous: LaunchAndEventsList

) {


}

