/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.models.AstronautFlight

class AstronautFlightTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AstronautFlight
        //val modelInstance = AstronautFlight()

        // to test the property `launchId`
        should("test launchId") {
            // uncomment below to test the property
            //modelInstance.launchId shouldBe ("TODO")
        }

        // to test the property `launchName`
        should("test launchName") {
            // uncomment below to test the property
            //modelInstance.launchName shouldBe ("TODO")
        }

        // to test the property `net`
        should("test net") {
            // uncomment below to test the property
            //modelInstance.net shouldBe ("TODO")
        }

    }
}
