/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.models.LauncherConfigSummary

class LauncherConfigSummaryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LauncherConfigSummary
        //val modelInstance = LauncherConfigSummary()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `fullName`
        should("test fullName") {
            // uncomment below to test the property
            //modelInstance.fullName shouldBe ("TODO")
        }

        // to test the property `variant`
        should("test variant") {
            // uncomment below to test the property
            //modelInstance.variant shouldBe ("TODO")
        }

        // to test the property `active`
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

        // to test the property `reusable`
        should("test reusable") {
            // uncomment below to test the property
            //modelInstance.reusable shouldBe ("TODO")
        }

        // to test the property `manufacturerId`
        should("test manufacturerId") {
            // uncomment below to test the property
            //modelInstance.manufacturerId shouldBe ("TODO")
        }

        // to test the property `imageUrl`
        should("test imageUrl") {
            // uncomment below to test the property
            //modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `infoUrl`
        should("test infoUrl") {
            // uncomment below to test the property
            //modelInstance.infoUrl shouldBe ("TODO")
        }

        // to test the property `wikiUrl`
        should("test wikiUrl") {
            // uncomment below to test the property
            //modelInstance.wikiUrl shouldBe ("TODO")
        }

    }
}
