/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.models.LauncherSummary

class LauncherSummaryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LauncherSummary
        //val modelInstance = LauncherSummary()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `serialNumber`
        should("test serialNumber") {
            // uncomment below to test the property
            //modelInstance.serialNumber shouldBe ("TODO")
        }

        // to test the property `flightProven`
        should("test flightProven") {
            // uncomment below to test the property
            //modelInstance.flightProven shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `flights`
        should("test flights") {
            // uncomment below to test the property
            //modelInstance.flights shouldBe ("TODO")
        }

        // to test the property `successfulLandings`
        should("test successfulLandings") {
            // uncomment below to test the property
            //modelInstance.successfulLandings shouldBe ("TODO")
        }

        // to test the property `attemptedLandings`
        should("test attemptedLandings") {
            // uncomment below to test the property
            //modelInstance.attemptedLandings shouldBe ("TODO")
        }

        // to test the property `details`
        should("test details") {
            // uncomment below to test the property
            //modelInstance.details shouldBe ("TODO")
        }

    }
}
