/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.models.StationDetail
import me.calebjones.spacelaunchnow.api.trantor.models.Expedition

class StationDetailTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StationDetail
        //val modelInstance = StationDetail()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `statusId`
        should("test statusId") {
            // uncomment below to test the property
            //modelInstance.statusId shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `typeId`
        should("test typeId") {
            // uncomment below to test the property
            //modelInstance.typeId shouldBe ("TODO")
        }

        // to test the property `imageUrl`
        should("test imageUrl") {
            // uncomment below to test the property
            //modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `orbit`
        should("test orbit") {
            // uncomment below to test the property
            //modelInstance.orbit shouldBe ("TODO")
        }

        // to test the property `founded`
        should("test founded") {
            // uncomment below to test the property
            //modelInstance.founded shouldBe ("TODO")
        }

        // to test the property `deorbited`
        should("test deorbited") {
            // uncomment below to test the property
            //modelInstance.deorbited shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `width`
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `mass`
        should("test mass") {
            // uncomment below to test the property
            //modelInstance.mass shouldBe ("TODO")
        }

        // to test the property `volume`
        should("test volume") {
            // uncomment below to test the property
            //modelInstance.volume shouldBe ("TODO")
        }

        // to test the property `onboardCrew`
        should("test onboardCrew") {
            // uncomment below to test the property
            //modelInstance.onboardCrew shouldBe ("TODO")
        }

        // to test the property `dockedVehicles`
        should("test dockedVehicles") {
            // uncomment below to test the property
            //modelInstance.dockedVehicles shouldBe ("TODO")
        }

        // to test the property `ownerIds`
        should("test ownerIds") {
            // uncomment below to test the property
            //modelInstance.ownerIds shouldBe ("TODO")
        }

        // to test the property `ownerNames`
        should("test ownerNames") {
            // uncomment below to test the property
            //modelInstance.ownerNames shouldBe ("TODO")
        }

        // to test the property `expeditions`
        should("test expeditions") {
            // uncomment below to test the property
            //modelInstance.expeditions shouldBe ("TODO")
        }

    }
}
