/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.models.TimelineEvent

class TimelineEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TimelineEvent
        //val modelInstance = TimelineEvent()

        // to test the property `abbrev`
        should("test abbrev") {
            // uncomment below to test the property
            //modelInstance.abbrev shouldBe ("TODO")
        }

        // to test the property `relativeTime`
        should("test relativeTime") {
            // uncomment below to test the property
            //modelInstance.relativeTime shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

    }
}
