/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.models.UpdateList

class UpdateListTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateList
        //val modelInstance = UpdateList()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `comment`
        should("test comment") {
            // uncomment below to test the property
            //modelInstance.comment shouldBe ("TODO")
        }

        // to test the property `infoUrl`
        should("test infoUrl") {
            // uncomment below to test the property
            //modelInstance.infoUrl shouldBe ("TODO")
        }

        // to test the property `createdBy`
        should("test createdBy") {
            // uncomment below to test the property
            //modelInstance.createdBy shouldBe ("TODO")
        }

        // to test the property `createdOn`
        should("test createdOn") {
            // uncomment below to test the property
            //modelInstance.createdOn shouldBe ("TODO")
        }

        // to test the property `launchId`
        should("test launchId") {
            // uncomment below to test the property
            //modelInstance.launchId shouldBe ("TODO")
        }

        // to test the property `launchName`
        should("test launchName") {
            // uncomment below to test the property
            //modelInstance.launchName shouldBe ("TODO")
        }

        // to test the property `eventId`
        should("test eventId") {
            // uncomment below to test the property
            //modelInstance.eventId shouldBe ("TODO")
        }

        // to test the property `eventName`
        should("test eventName") {
            // uncomment below to test the property
            //modelInstance.eventName shouldBe ("TODO")
        }

        // to test the property `programId`
        should("test programId") {
            // uncomment below to test the property
            //modelInstance.programId shouldBe ("TODO")
        }

        // to test the property `profileImage`
        should("test profileImage") {
            // uncomment below to test the property
            //modelInstance.profileImage shouldBe ("TODO")
        }

    }
}
