/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.trantor.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.trantor.models.ValidationError
import me.calebjones.spacelaunchnow.api.trantor.models.ValidationErrorLocInner

class ValidationErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ValidationError
        //val modelInstance = ValidationError()

        // to test the property `loc`
        should("test loc") {
            // uncomment below to test the property
            //modelInstance.loc shouldBe ("TODO")
        }

        // to test the property `msg`
        should("test msg") {
            // uncomment below to test the property
            //modelInstance.msg shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `input`
        should("test input") {
            // uncomment below to test the property
            //modelInstance.input shouldBe ("TODO")
        }

        // to test the property `ctx`
        should("test ctx") {
            // uncomment below to test the property
            //modelInstance.ctx shouldBe ("TODO")
        }

    }
}
