/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.launchlibrary.models.DockingLocation
import me.calebjones.spacelaunchnow.api.launchlibrary.models.PayloadMini
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpaceStationMini
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpacecraftConfigNormal

class DockingLocationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DockingLocation
        //val modelInstance = DockingLocation()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `spacestation`
        should("test spacestation") {
            // uncomment below to test the property
            //modelInstance.spacestation shouldBe ("TODO")
        }

        // to test the property `spacecraft`
        should("test spacecraft") {
            // uncomment below to test the property
            //modelInstance.spacecraft shouldBe ("TODO")
        }

        // to test the property `payload`
        should("test payload") {
            // uncomment below to test the property
            //modelInstance.payload shouldBe ("TODO")
        }

    }
}
