/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.launchlibrary.models.EventMini
import me.calebjones.spacelaunchnow.api.launchlibrary.models.Image
import me.calebjones.spacelaunchnow.api.launchlibrary.models.InfoURL
import me.calebjones.spacelaunchnow.api.launchlibrary.models.VidURL

class EventMiniTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EventMini
        //val modelInstance = EventMini()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `infoUrls`
        should("test infoUrls") {
            // uncomment below to test the property
            //modelInstance.infoUrls shouldBe ("TODO")
        }

        // to test the property `vidUrls`
        should("test vidUrls") {
            // uncomment below to test the property
            //modelInstance.vidUrls shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `date`
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

    }
}
