/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.launchlibrary.models.LaunchAndEventsDetailed
import me.calebjones.spacelaunchnow.api.launchlibrary.models.EventNormal
import me.calebjones.spacelaunchnow.api.launchlibrary.models.LaunchDetailed

class LaunchAndEventsDetailedTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LaunchAndEventsDetailed
        //val modelInstance = LaunchAndEventsDetailed()

        // to test the property `launches`
        should("test launches") {
            // uncomment below to test the property
            //modelInstance.launches shouldBe ("TODO")
        }

        // to test the property `events`
        should("test events") {
            // uncomment below to test the property
            //modelInstance.events shouldBe ("TODO")
        }

    }
}
