/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.launchlibrary.models.LauncherDetailed
import me.calebjones.spacelaunchnow.api.launchlibrary.models.Image
import me.calebjones.spacelaunchnow.api.launchlibrary.models.LauncherConfigList
import me.calebjones.spacelaunchnow.api.launchlibrary.models.LauncherStatus

class LauncherDetailedTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LauncherDetailed
        //val modelInstance = LauncherDetailed()

        // to test the property `responseMode`
        should("test responseMode") {
            // uncomment below to test the property
            //modelInstance.responseMode shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `serialNumber`
        should("test serialNumber") {
            // uncomment below to test the property
            //modelInstance.serialNumber shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `details`
        should("test details") {
            // uncomment below to test the property
            //modelInstance.details shouldBe ("TODO")
        }

        // to test the property `successfulLandings`
        should("test successfulLandings") {
            // uncomment below to test the property
            //modelInstance.successfulLandings shouldBe ("TODO")
        }

        // to test the property `attemptedLandings`
        should("test attemptedLandings") {
            // uncomment below to test the property
            //modelInstance.attemptedLandings shouldBe ("TODO")
        }

        // to test the property `flights`
        should("test flights") {
            // uncomment below to test the property
            //modelInstance.flights shouldBe ("TODO")
        }

        // to test the property `lastLaunchDate`
        should("test lastLaunchDate") {
            // uncomment below to test the property
            //modelInstance.lastLaunchDate shouldBe ("TODO")
        }

        // to test the property `firstLaunchDate`
        should("test firstLaunchDate") {
            // uncomment below to test the property
            //modelInstance.firstLaunchDate shouldBe ("TODO")
        }

        // to test the property `fastestTurnaround`
        should("test fastestTurnaround") {
            // uncomment below to test the property
            //modelInstance.fastestTurnaround shouldBe ("TODO")
        }

        // to test the property `launcherConfig`
        should("test launcherConfig") {
            // uncomment below to test the property
            //modelInstance.launcherConfig shouldBe ("TODO")
        }

        // to test the property `flightProven`
        should("test flightProven") {
            // uncomment below to test the property
            //modelInstance.flightProven shouldBe ("TODO")
        }

        // to test the property `isPlaceholder`
        should("test isPlaceholder") {
            // uncomment below to test the property
            //modelInstance.isPlaceholder shouldBe ("TODO")
        }

    }
}
