/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.launchlibrary.models.PaginatedLaunchDetailedList
import me.calebjones.spacelaunchnow.api.launchlibrary.models.LaunchDetailed

class PaginatedLaunchDetailedListTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaginatedLaunchDetailedList
        //val modelInstance = PaginatedLaunchDetailedList()

        // to test the property `count`
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `results`
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

        // to test the property `next`
        should("test next") {
            // uncomment below to test the property
            //modelInstance.next shouldBe ("TODO")
        }

        // to test the property `previous`
        should("test previous") {
            // uncomment below to test the property
            //modelInstance.previous shouldBe ("TODO")
        }

    }
}
