/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpacecraftConfigDetailed
import me.calebjones.spacelaunchnow.api.launchlibrary.models.AgencyNormal
import me.calebjones.spacelaunchnow.api.launchlibrary.models.Image
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpacecraftConfigFamilyDetailed
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpacecraftConfigType

class SpacecraftConfigDetailedTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SpacecraftConfigDetailed
        //val modelInstance = SpacecraftConfigDetailed()

        // to test the property `responseMode`
        should("test responseMode") {
            // uncomment below to test the property
            //modelInstance.responseMode shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `agency`
        should("test agency") {
            // uncomment below to test the property
            //modelInstance.agency shouldBe ("TODO")
        }

        // to test the property `family`
        should("test family") {
            // uncomment below to test the property
            //modelInstance.family shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `fastestTurnaround`
        should("test fastestTurnaround") {
            // uncomment below to test the property
            //modelInstance.fastestTurnaround shouldBe ("TODO")
        }

        // to test the property `inUse`
        should("test inUse") {
            // uncomment below to test the property
            //modelInstance.inUse shouldBe ("TODO")
        }

        // to test the property `capability`
        should("test capability") {
            // uncomment below to test the property
            //modelInstance.capability shouldBe ("TODO")
        }

        // to test the property `history`
        should("test history") {
            // uncomment below to test the property
            //modelInstance.history shouldBe ("TODO")
        }

        // to test the property `details`
        should("test details") {
            // uncomment below to test the property
            //modelInstance.details shouldBe ("TODO")
        }

        // to test the property `maidenFlight`
        should("test maidenFlight") {
            // uncomment below to test the property
            //modelInstance.maidenFlight shouldBe ("TODO")
        }

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `diameter`
        should("test diameter") {
            // uncomment below to test the property
            //modelInstance.diameter shouldBe ("TODO")
        }

        // to test the property `humanRated`
        should("test humanRated") {
            // uncomment below to test the property
            //modelInstance.humanRated shouldBe ("TODO")
        }

        // to test the property `crewCapacity`
        should("test crewCapacity") {
            // uncomment below to test the property
            //modelInstance.crewCapacity shouldBe ("TODO")
        }

        // to test the property `payloadCapacity`
        should("test payloadCapacity") {
            // uncomment below to test the property
            //modelInstance.payloadCapacity shouldBe ("TODO")
        }

        // to test the property `payloadReturnCapacity`
        should("test payloadReturnCapacity") {
            // uncomment below to test the property
            //modelInstance.payloadReturnCapacity shouldBe ("TODO")
        }

        // to test the property `flightLife`
        should("test flightLife") {
            // uncomment below to test the property
            //modelInstance.flightLife shouldBe ("TODO")
        }

        // to test the property `wikiLink`
        should("test wikiLink") {
            // uncomment below to test the property
            //modelInstance.wikiLink shouldBe ("TODO")
        }

        // to test the property `infoLink`
        should("test infoLink") {
            // uncomment below to test the property
            //modelInstance.infoLink shouldBe ("TODO")
        }

        // to test the property `spacecraftFlown`
        should("test spacecraftFlown") {
            // uncomment below to test the property
            //modelInstance.spacecraftFlown shouldBe ("TODO")
        }

        // to test the property `totalLaunchCount`
        should("test totalLaunchCount") {
            // uncomment below to test the property
            //modelInstance.totalLaunchCount shouldBe ("TODO")
        }

        // to test the property `successfulLaunches`
        should("test successfulLaunches") {
            // uncomment below to test the property
            //modelInstance.successfulLaunches shouldBe ("TODO")
        }

        // to test the property `failedLaunches`
        should("test failedLaunches") {
            // uncomment below to test the property
            //modelInstance.failedLaunches shouldBe ("TODO")
        }

        // to test the property `attemptedLandings`
        should("test attemptedLandings") {
            // uncomment below to test the property
            //modelInstance.attemptedLandings shouldBe ("TODO")
        }

        // to test the property `successfulLandings`
        should("test successfulLandings") {
            // uncomment below to test the property
            //modelInstance.successfulLandings shouldBe ("TODO")
        }

        // to test the property `failedLandings`
        should("test failedLandings") {
            // uncomment below to test the property
            //modelInstance.failedLandings shouldBe ("TODO")
        }

    }
}
