/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.launchlibrary.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpaceStationDetailedEndpoint
import me.calebjones.spacelaunchnow.api.launchlibrary.models.AgencyNormal
import me.calebjones.spacelaunchnow.api.launchlibrary.models.DockingEventForChaserNormal
import me.calebjones.spacelaunchnow.api.launchlibrary.models.DockingLocationSerializerForSpacestation
import me.calebjones.spacelaunchnow.api.launchlibrary.models.ExpeditionMini
import me.calebjones.spacelaunchnow.api.launchlibrary.models.Image
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpaceStationStatus
import me.calebjones.spacelaunchnow.api.launchlibrary.models.SpaceStationType

class SpaceStationDetailedEndpointTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SpaceStationDetailedEndpoint
        //val modelInstance = SpaceStationDetailedEndpoint()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `founded`
        should("test founded") {
            // uncomment below to test the property
            //modelInstance.founded shouldBe ("TODO")
        }

        // to test the property `deorbited`
        should("test deorbited") {
            // uncomment below to test the property
            //modelInstance.deorbited shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `orbit`
        should("test orbit") {
            // uncomment below to test the property
            //modelInstance.orbit shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `owners`
        should("test owners") {
            // uncomment below to test the property
            //modelInstance.owners shouldBe ("TODO")
        }

        // to test the property `responseMode`
        should("test responseMode") {
            // uncomment below to test the property
            //modelInstance.responseMode shouldBe ("TODO")
        }

        // to test the property `activeExpeditions`
        should("test activeExpeditions") {
            // uncomment below to test the property
            //modelInstance.activeExpeditions shouldBe ("TODO")
        }

        // to test the property `dockingLocation`
        should("test dockingLocation") {
            // uncomment below to test the property
            //modelInstance.dockingLocation shouldBe ("TODO")
        }

        // to test the property `activeDockingEvents`
        should("test activeDockingEvents") {
            // uncomment below to test the property
            //modelInstance.activeDockingEvents shouldBe ("TODO")
        }

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `width`
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `mass`
        should("test mass") {
            // uncomment below to test the property
            //modelInstance.mass shouldBe ("TODO")
        }

        // to test the property `volume`
        should("test volume") {
            // uncomment below to test the property
            //modelInstance.volume shouldBe ("TODO")
        }

        // to test the property `onboardCrew`
        should("test onboardCrew") {
            // uncomment below to test the property
            //modelInstance.onboardCrew shouldBe ("TODO")
        }

        // to test the property `dockedVehicles`
        should("test dockedVehicles") {
            // uncomment below to test the property
            //modelInstance.dockedVehicles shouldBe ("TODO")
        }

    }
}
