/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.snapi.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.snapi.apis.InfoApi
import me.calebjones.spacelaunchnow.api.snapi.models.Info

class InfoApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InfoApi
        //val apiInstance = InfoApi()

        // to test infoRetrieve
        should("test infoRetrieve") {
            // uncomment below to test infoRetrieve
            //val result : Info = apiInstance.infoRetrieve()
            //result shouldBe ("TODO")
        }

    }
}
