/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.models.FirstStageNormalSerializerNoLanding
import me.calebjones.spacelaunchnow.api.models.LaunchMini
import me.calebjones.spacelaunchnow.api.models.LauncherNormal

class FirstStageNormalSerializerNoLandingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FirstStageNormalSerializerNoLanding
        //val modelInstance = FirstStageNormalSerializerNoLanding()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `launcher`
        should("test launcher") {
            // uncomment below to test the property
            //modelInstance.launcher shouldBe ("TODO")
        }

        // to test the property `turnAroundTime`
        should("test turnAroundTime") {
            // uncomment below to test the property
            //modelInstance.turnAroundTime shouldBe ("TODO")
        }

        // to test the property `previousFlight`
        should("test previousFlight") {
            // uncomment below to test the property
            //modelInstance.previousFlight shouldBe ("TODO")
        }

        // to test the property `reused`
        should("test reused") {
            // uncomment below to test the property
            //modelInstance.reused shouldBe ("TODO")
        }

        // to test the property `launcherFlightNumber`
        should("test launcherFlightNumber") {
            // uncomment below to test the property
            //modelInstance.launcherFlightNumber shouldBe ("TODO")
        }

        // to test the property `previousFlightDate`
        should("test previousFlightDate") {
            // uncomment below to test the property
            //modelInstance.previousFlightDate shouldBe ("TODO")
        }

    }
}
