/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.models.LandingLocation
import me.calebjones.spacelaunchnow.api.models.CelestialBodyNormal
import me.calebjones.spacelaunchnow.api.models.Image
import me.calebjones.spacelaunchnow.api.models.LocationDetailedSerializerNoCelestialBody

class LandingLocationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LandingLocation
        //val modelInstance = LandingLocation()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `location`
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `celestialBody`
        should("test celestialBody") {
            // uncomment below to test the property
            //modelInstance.celestialBody shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `active`
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

        // to test the property `abbrev`
        should("test abbrev") {
            // uncomment below to test the property
            //modelInstance.abbrev shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `longitude`
        should("test longitude") {
            // uncomment below to test the property
            //modelInstance.longitude shouldBe ("TODO")
        }

        // to test the property `latitude`
        should("test latitude") {
            // uncomment below to test the property
            //modelInstance.latitude shouldBe ("TODO")
        }

        // to test the property `successfulLandings`
        should("test successfulLandings") {
            // uncomment below to test the property
            //modelInstance.successfulLandings shouldBe ("TODO")
        }

        // to test the property `attemptedLandings`
        should("test attemptedLandings") {
            // uncomment below to test the property
            //modelInstance.attemptedLandings shouldBe ("TODO")
        }

        // to test the property `failedLandings`
        should("test failedLandings") {
            // uncomment below to test the property
            //modelInstance.failedLandings shouldBe ("TODO")
        }

    }
}
