/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.models.LauncherConfigFamilyNormal
import me.calebjones.spacelaunchnow.api.models.AgencyNormal
import me.calebjones.spacelaunchnow.api.models.LauncherConfigFamilyMini

class LauncherConfigFamilyNormalTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LauncherConfigFamilyNormal
        //val modelInstance = LauncherConfigFamilyNormal()

        // to test the property `responseMode`
        should("test responseMode") {
            // uncomment below to test the property
            //modelInstance.responseMode shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `manufacturer`
        should("test manufacturer") {
            // uncomment below to test the property
            //modelInstance.manufacturer shouldBe ("TODO")
        }

        // to test the property `parent`
        should("test parent") {
            // uncomment below to test the property
            //modelInstance.parent shouldBe ("TODO")
        }

    }
}
