/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.models.LaunchDetailed
import me.calebjones.spacelaunchnow.api.models.AgencyDetailed
import me.calebjones.spacelaunchnow.api.models.Image
import me.calebjones.spacelaunchnow.api.models.InfoURL
import me.calebjones.spacelaunchnow.api.models.LaunchStatus
import me.calebjones.spacelaunchnow.api.models.Mission
import me.calebjones.spacelaunchnow.api.models.MissionPatch
import me.calebjones.spacelaunchnow.api.models.NetPrecision
import me.calebjones.spacelaunchnow.api.models.PadDetailed
import me.calebjones.spacelaunchnow.api.models.ProgramNormal
import me.calebjones.spacelaunchnow.api.models.RocketDetailed
import me.calebjones.spacelaunchnow.api.models.TimelineEvent
import me.calebjones.spacelaunchnow.api.models.Update
import me.calebjones.spacelaunchnow.api.models.VidURL

class LaunchDetailedTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LaunchDetailed
        //val modelInstance = LaunchDetailed()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `responseMode`
        should("test responseMode") {
            // uncomment below to test the property
            //modelInstance.responseMode shouldBe ("TODO")
        }

        // to test the property `slug`
        should("test slug") {
            // uncomment below to test the property
            //modelInstance.slug shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `netPrecision`
        should("test netPrecision") {
            // uncomment below to test the property
            //modelInstance.netPrecision shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `launchServiceProvider`
        should("test launchServiceProvider") {
            // uncomment below to test the property
            //modelInstance.launchServiceProvider shouldBe ("TODO")
        }

        // to test the property `infographic`
        should("test infographic") {
            // uncomment below to test the property
            //modelInstance.infographic shouldBe ("TODO")
        }

        // to test the property `rocket`
        should("test rocket") {
            // uncomment below to test the property
            //modelInstance.rocket shouldBe ("TODO")
        }

        // to test the property `mission`
        should("test mission") {
            // uncomment below to test the property
            //modelInstance.mission shouldBe ("TODO")
        }

        // to test the property `pad`
        should("test pad") {
            // uncomment below to test the property
            //modelInstance.pad shouldBe ("TODO")
        }

        // to test the property `program`
        should("test program") {
            // uncomment below to test the property
            //modelInstance.program shouldBe ("TODO")
        }

        // to test the property `updates`
        should("test updates") {
            // uncomment below to test the property
            //modelInstance.updates shouldBe ("TODO")
        }

        // to test the property `infoUrls`
        should("test infoUrls") {
            // uncomment below to test the property
            //modelInstance.infoUrls shouldBe ("TODO")
        }

        // to test the property `vidUrls`
        should("test vidUrls") {
            // uncomment below to test the property
            //modelInstance.vidUrls shouldBe ("TODO")
        }

        // to test the property `timeline`
        should("test timeline") {
            // uncomment below to test the property
            //modelInstance.timeline shouldBe ("TODO")
        }

        // to test the property `padTurnaround`
        should("test padTurnaround") {
            // uncomment below to test the property
            //modelInstance.padTurnaround shouldBe ("TODO")
        }

        // to test the property `missionPatches`
        should("test missionPatches") {
            // uncomment below to test the property
            //modelInstance.missionPatches shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `launchDesignator`
        should("test launchDesignator") {
            // uncomment below to test the property
            //modelInstance.launchDesignator shouldBe ("TODO")
        }

        // to test the property `lastUpdated`
        should("test lastUpdated") {
            // uncomment below to test the property
            //modelInstance.lastUpdated shouldBe ("TODO")
        }

        // to test the property `net`
        should("test net") {
            // uncomment below to test the property
            //modelInstance.net shouldBe ("TODO")
        }

        // to test the property `windowEnd`
        should("test windowEnd") {
            // uncomment below to test the property
            //modelInstance.windowEnd shouldBe ("TODO")
        }

        // to test the property `windowStart`
        should("test windowStart") {
            // uncomment below to test the property
            //modelInstance.windowStart shouldBe ("TODO")
        }

        // to test the property `probability`
        should("test probability") {
            // uncomment below to test the property
            //modelInstance.probability shouldBe ("TODO")
        }

        // to test the property `weatherConcerns`
        should("test weatherConcerns") {
            // uncomment below to test the property
            //modelInstance.weatherConcerns shouldBe ("TODO")
        }

        // to test the property `failreason`
        should("test failreason") {
            // uncomment below to test the property
            //modelInstance.failreason shouldBe ("TODO")
        }

        // to test the property `hashtag`
        should("test hashtag") {
            // uncomment below to test the property
            //modelInstance.hashtag shouldBe ("TODO")
        }

        // to test the property `webcastLive`
        should("test webcastLive") {
            // uncomment below to test the property
            //modelInstance.webcastLive shouldBe ("TODO")
        }

        // to test the property `orbitalLaunchAttemptCount`
        should("test orbitalLaunchAttemptCount") {
            // uncomment below to test the property
            //modelInstance.orbitalLaunchAttemptCount shouldBe ("TODO")
        }

        // to test the property `locationLaunchAttemptCount`
        should("test locationLaunchAttemptCount") {
            // uncomment below to test the property
            //modelInstance.locationLaunchAttemptCount shouldBe ("TODO")
        }

        // to test the property `padLaunchAttemptCount`
        should("test padLaunchAttemptCount") {
            // uncomment below to test the property
            //modelInstance.padLaunchAttemptCount shouldBe ("TODO")
        }

        // to test the property `agencyLaunchAttemptCount`
        should("test agencyLaunchAttemptCount") {
            // uncomment below to test the property
            //modelInstance.agencyLaunchAttemptCount shouldBe ("TODO")
        }

        // to test the property `orbitalLaunchAttemptCountYear`
        should("test orbitalLaunchAttemptCountYear") {
            // uncomment below to test the property
            //modelInstance.orbitalLaunchAttemptCountYear shouldBe ("TODO")
        }

        // to test the property `locationLaunchAttemptCountYear`
        should("test locationLaunchAttemptCountYear") {
            // uncomment below to test the property
            //modelInstance.locationLaunchAttemptCountYear shouldBe ("TODO")
        }

        // to test the property `padLaunchAttemptCountYear`
        should("test padLaunchAttemptCountYear") {
            // uncomment below to test the property
            //modelInstance.padLaunchAttemptCountYear shouldBe ("TODO")
        }

        // to test the property `agencyLaunchAttemptCountYear`
        should("test agencyLaunchAttemptCountYear") {
            // uncomment below to test the property
            //modelInstance.agencyLaunchAttemptCountYear shouldBe ("TODO")
        }

        // to test the property `flightclubUrl`
        should("test flightclubUrl") {
            // uncomment below to test the property
            //modelInstance.flightclubUrl shouldBe ("TODO")
        }

    }
}
