/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.models.Mission
import me.calebjones.spacelaunchnow.api.models.AgencyMini
import me.calebjones.spacelaunchnow.api.models.Image
import me.calebjones.spacelaunchnow.api.models.InfoURL
import me.calebjones.spacelaunchnow.api.models.Orbit
import me.calebjones.spacelaunchnow.api.models.VidURL

class MissionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Mission
        //val modelInstance = Mission()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `orbit`
        should("test orbit") {
            // uncomment below to test the property
            //modelInstance.orbit shouldBe ("TODO")
        }

        // to test the property `agencies`
        should("test agencies") {
            // uncomment below to test the property
            //modelInstance.agencies shouldBe ("TODO")
        }

        // to test the property `infoUrls`
        should("test infoUrls") {
            // uncomment below to test the property
            //modelInstance.infoUrls shouldBe ("TODO")
        }

        // to test the property `vidUrls`
        should("test vidUrls") {
            // uncomment below to test the property
            //modelInstance.vidUrls shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

    }
}
