/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.models.PayloadMini
import me.calebjones.spacelaunchnow.api.models.AgencyMini
import me.calebjones.spacelaunchnow.api.models.Image
import me.calebjones.spacelaunchnow.api.models.PayloadType

class PayloadMiniTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PayloadMini
        //val modelInstance = PayloadMini()

        // to test the property `responseMode`
        should("test responseMode") {
            // uncomment below to test the property
            //modelInstance.responseMode shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `manufacturer`
        should("test manufacturer") {
            // uncomment below to test the property
            //modelInstance.manufacturer shouldBe ("TODO")
        }

        // to test the property ``operator``
        should("test `operator`") {
            // uncomment below to test the property
            //modelInstance.`operator` shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
