/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.models.PayloadFlightDetailedSerializerNoLanding
import me.calebjones.spacelaunchnow.api.models.DockingEventForChaserNormal
import me.calebjones.spacelaunchnow.api.models.LaunchNormal
import me.calebjones.spacelaunchnow.api.models.PayloadDetailed

class PayloadFlightDetailedSerializerNoLandingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PayloadFlightDetailedSerializerNoLanding
        //val modelInstance = PayloadFlightDetailedSerializerNoLanding()

        // to test the property `responseMode`
        should("test responseMode") {
            // uncomment below to test the property
            //modelInstance.responseMode shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `payload`
        should("test payload") {
            // uncomment below to test the property
            //modelInstance.payload shouldBe ("TODO")
        }

        // to test the property `launch`
        should("test launch") {
            // uncomment below to test the property
            //modelInstance.launch shouldBe ("TODO")
        }

        // to test the property `dockingEvents`
        should("test dockingEvents") {
            // uncomment below to test the property
            //modelInstance.dockingEvents shouldBe ("TODO")
        }

        // to test the property `destination`
        should("test destination") {
            // uncomment below to test the property
            //modelInstance.destination shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

    }
}
