/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.models.SpacecraftConfigFamilyNormal
import me.calebjones.spacelaunchnow.api.models.AgencyMini
import me.calebjones.spacelaunchnow.api.models.SpacecraftConfigFamilyMini

class SpacecraftConfigFamilyNormalTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SpacecraftConfigFamilyNormal
        //val modelInstance = SpacecraftConfigFamilyNormal()

        // to test the property `responseMode`
        should("test responseMode") {
            // uncomment below to test the property
            //modelInstance.responseMode shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `manufacturer`
        should("test manufacturer") {
            // uncomment below to test the property
            //modelInstance.manufacturer shouldBe ("TODO")
        }

        // to test the property `parent`
        should("test parent") {
            // uncomment below to test the property
            //modelInstance.parent shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `maidenFlight`
        should("test maidenFlight") {
            // uncomment below to test the property
            //modelInstance.maidenFlight shouldBe ("TODO")
        }

    }
}
