/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.models.SpacecraftConfigNormal
import me.calebjones.spacelaunchnow.api.models.AgencyMini
import me.calebjones.spacelaunchnow.api.models.Image
import me.calebjones.spacelaunchnow.api.models.SpacecraftConfigFamilyNormal
import me.calebjones.spacelaunchnow.api.models.SpacecraftConfigType

class SpacecraftConfigNormalTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SpacecraftConfigNormal
        //val modelInstance = SpacecraftConfigNormal()

        // to test the property `responseMode`
        should("test responseMode") {
            // uncomment below to test the property
            //modelInstance.responseMode shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `agency`
        should("test agency") {
            // uncomment below to test the property
            //modelInstance.agency shouldBe ("TODO")
        }

        // to test the property `family`
        should("test family") {
            // uncomment below to test the property
            //modelInstance.family shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `inUse`
        should("test inUse") {
            // uncomment below to test the property
            //modelInstance.inUse shouldBe ("TODO")
        }

    }
}
