/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.models.VidURL
import me.calebjones.spacelaunchnow.api.models.Language
import me.calebjones.spacelaunchnow.api.models.VidURLType

class VidURLTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VidURL
        //val modelInstance = VidURL()

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `language`
        should("test language") {
            // uncomment below to test the property
            //modelInstance.language shouldBe ("TODO")
        }

        // to test the property `priority`
        should("test priority") {
            // uncomment below to test the property
            //modelInstance.priority shouldBe ("TODO")
        }

        // to test the property `source`
        should("test source") {
            // uncomment below to test the property
            //modelInstance.source shouldBe ("TODO")
        }

        // to test the property `publisher`
        should("test publisher") {
            // uncomment below to test the property
            //modelInstance.publisher shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `featureImage`
        should("test featureImage") {
            // uncomment below to test the property
            //modelInstance.featureImage shouldBe ("TODO")
        }

        // to test the property `startTime`
        should("test startTime") {
            // uncomment below to test the property
            //modelInstance.startTime shouldBe ("TODO")
        }

        // to test the property `endTime`
        should("test endTime") {
            // uncomment below to test the property
            //modelInstance.endTime shouldBe ("TODO")
        }

        // to test the property `live`
        should("test live") {
            // uncomment below to test the property
            //modelInstance.live shouldBe ("TODO")
        }

    }
}
