/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.apis.DockingEventsApi
import me.calebjones.spacelaunchnow.api.models.DockingEventEndpointNormal
import me.calebjones.spacelaunchnow.api.models.PaginatedDockingEventEndpointNormalList

class DockingEventsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DockingEventsApi
        //val apiInstance = DockingEventsApi()

        // to test dockingEventsList
        should("test dockingEventsList") {
            // uncomment below to test dockingEventsList
            //val dockingDay : kotlin.collections.List<kotlin.Double> =  // kotlin.collections.List<kotlin.Double> | Multiple values may be separated by commas.
            //val dockingGt : kotlinx.datetime.Instant = 2013-10-20T19:20:30+01:00 // kotlinx.datetime.Instant | Docking is greater than
            //val dockingGte : kotlinx.datetime.Instant = 2013-10-20T19:20:30+01:00 // kotlinx.datetime.Instant | Docking is greater than or equal to
            //val dockingLt : kotlinx.datetime.Instant = 2013-10-20T19:20:30+01:00 // kotlinx.datetime.Instant | Docking is less than
            //val dockingLte : kotlinx.datetime.Instant = 2013-10-20T19:20:30+01:00 // kotlinx.datetime.Instant | Docking is less than or equal to
            //val dockingMonth : kotlin.collections.List<kotlin.Double> =  // kotlin.collections.List<kotlin.Double> | Multiple values may be separated by commas.
            //val dockingYear : kotlin.collections.List<kotlin.Double> =  // kotlin.collections.List<kotlin.Double> | Multiple values may be separated by commas.
            //val dockingLocationId : kotlin.Int = 56 // kotlin.Int | 
            //val flightVehicleChaserId : kotlin.Int = 56 // kotlin.Int | 
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results to return per page.
            //val offset : kotlin.Int = 56 // kotlin.Int | The initial index from which to return the results.
            //val ordering : kotlin.String = ordering_example // kotlin.String | Which field to use when ordering the results.
            //val search : kotlin.String = search_example // kotlin.String | A search term.
            //val spaceStationTargetId : kotlin.Int = 56 // kotlin.Int | 
            //val result : PaginatedDockingEventEndpointNormalList = apiInstance.dockingEventsList(dockingDay, dockingGt, dockingGte, dockingLt, dockingLte, dockingMonth, dockingYear, dockingLocationId, flightVehicleChaserId, limit, offset, ordering, search, spaceStationTargetId)
            //result shouldBe ("TODO")
        }

        // to test dockingEventsRetrieve
        should("test dockingEventsRetrieve") {
            // uncomment below to test dockingEventsRetrieve
            //val id : kotlin.Int = 56 // kotlin.Int | A unique integer value identifying this docking event.
            //val result : DockingEventEndpointNormal = apiInstance.dockingEventsRetrieve(id)
            //result shouldBe ("TODO")
        }

    }
}
