/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.apis.LandingsApi
import me.calebjones.spacelaunchnow.api.models.LandingEndpointDetailed
import me.calebjones.spacelaunchnow.api.models.PaginatedLandingEndpointDetailedList
import me.calebjones.spacelaunchnow.api.models.PaginatedLandingEndpointListList
import me.calebjones.spacelaunchnow.api.models.PaginatedLandingEndpointNormalList

class LandingsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LandingsApi
        //val apiInstance = LandingsApi()

        // to test landingsDetailedList
        should("test landingsDetailedList") {
            // uncomment below to test landingsDetailedList
            //val attempt : kotlin.Boolean = true // kotlin.Boolean | 
            //val firststageLaunchIds : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Multiple values may be separated by commas.
            //val landingLocationIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val landingTypeIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val launcherIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val launcherConfigIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val launcherSerialNumbers : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Multiple values may be separated by commas.
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results to return per page.
            //val offset : kotlin.Int = 56 // kotlin.Int | The initial index from which to return the results.
            //val ordering : kotlin.String = ordering_example // kotlin.String | Which field to use when ordering the results.
            //val search : kotlin.String = search_example // kotlin.String | A search term.
            //val spacecraftIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val spacecraftConfigIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val spacecraftLaunchIds : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Multiple values may be separated by commas.
            //val success : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : PaginatedLandingEndpointDetailedList = apiInstance.landingsDetailedList(attempt, firststageLaunchIds, landingLocationIds, landingTypeIds, launcherIds, launcherConfigIds, launcherSerialNumbers, limit, offset, ordering, search, spacecraftIds, spacecraftConfigIds, spacecraftLaunchIds, success)
            //result shouldBe ("TODO")
        }

        // to test landingsList
        should("test landingsList") {
            // uncomment below to test landingsList
            //val attempt : kotlin.Boolean = true // kotlin.Boolean | 
            //val firststageLaunchIds : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Multiple values may be separated by commas.
            //val landingLocationIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val landingTypeIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val launcherIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val launcherConfigIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val launcherSerialNumbers : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Multiple values may be separated by commas.
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results to return per page.
            //val offset : kotlin.Int = 56 // kotlin.Int | The initial index from which to return the results.
            //val ordering : kotlin.String = ordering_example // kotlin.String | Which field to use when ordering the results.
            //val search : kotlin.String = search_example // kotlin.String | A search term.
            //val spacecraftIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val spacecraftConfigIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val spacecraftLaunchIds : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Multiple values may be separated by commas.
            //val success : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : PaginatedLandingEndpointNormalList = apiInstance.landingsList(attempt, firststageLaunchIds, landingLocationIds, landingTypeIds, launcherIds, launcherConfigIds, launcherSerialNumbers, limit, offset, ordering, search, spacecraftIds, spacecraftConfigIds, spacecraftLaunchIds, success)
            //result shouldBe ("TODO")
        }

        // to test landingsMiniList
        should("test landingsMiniList") {
            // uncomment below to test landingsMiniList
            //val attempt : kotlin.Boolean = true // kotlin.Boolean | 
            //val firststageLaunchIds : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Multiple values may be separated by commas.
            //val landingLocationIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val landingTypeIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val launcherIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val launcherConfigIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val launcherSerialNumbers : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Multiple values may be separated by commas.
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results to return per page.
            //val offset : kotlin.Int = 56 // kotlin.Int | The initial index from which to return the results.
            //val ordering : kotlin.String = ordering_example // kotlin.String | Which field to use when ordering the results.
            //val search : kotlin.String = search_example // kotlin.String | A search term.
            //val spacecraftIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val spacecraftConfigIds : kotlin.collections.List<kotlin.Int> =  // kotlin.collections.List<kotlin.Int> | Multiple values may be separated by commas.
            //val spacecraftLaunchIds : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Multiple values may be separated by commas.
            //val success : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : PaginatedLandingEndpointListList = apiInstance.landingsMiniList(attempt, firststageLaunchIds, landingLocationIds, landingTypeIds, launcherIds, launcherConfigIds, launcherSerialNumbers, limit, offset, ordering, search, spacecraftIds, spacecraftConfigIds, spacecraftLaunchIds, success)
            //result shouldBe ("TODO")
        }

        // to test landingsRetrieve
        should("test landingsRetrieve") {
            // uncomment below to test landingsRetrieve
            //val id : kotlin.Int = 56 // kotlin.Int | A unique integer value identifying this landing.
            //val result : LandingEndpointDetailed = apiInstance.landingsRetrieve(id)
            //result shouldBe ("TODO")
        }

    }
}
