/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.apis.PayloadsApi
import me.calebjones.spacelaunchnow.api.models.PaginatedPayloadDetailedList
import me.calebjones.spacelaunchnow.api.models.PaginatedPayloadMiniList
import me.calebjones.spacelaunchnow.api.models.PaginatedPayloadNormalList
import me.calebjones.spacelaunchnow.api.models.PayloadDetailed

class PayloadsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PayloadsApi
        //val apiInstance = PayloadsApi()

        // to test payloadsDetailedList
        should("test payloadsDetailedList") {
            // uncomment below to test payloadsDetailedList
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results to return per page.
            //val manufacturerId : kotlin.Int = 56 // kotlin.Int | 
            //val manufacturerName : kotlin.String = manufacturerName_example // kotlin.String | 
            //val name : kotlin.String = name_example // kotlin.String | 
            //val offset : kotlin.Int = 56 // kotlin.Int | The initial index from which to return the results.
            //val `operator` : kotlin.Int = 56 // kotlin.Int | 
            //val operatorId : kotlin.Int = 56 // kotlin.Int | 
            //val operatorName : kotlin.String = operatorName_example // kotlin.String | 
            //val ordering : kotlin.String = ordering_example // kotlin.String | Which field to use when ordering the results.
            //val programId : kotlin.Int = 56 // kotlin.Int | 
            //val search : kotlin.String = search_example // kotlin.String | A search term.
            //val result : PaginatedPayloadDetailedList = apiInstance.payloadsDetailedList(limit, manufacturerId, manufacturerName, name, offset, `operator`, operatorId, operatorName, ordering, programId, search)
            //result shouldBe ("TODO")
        }

        // to test payloadsList
        should("test payloadsList") {
            // uncomment below to test payloadsList
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results to return per page.
            //val manufacturerId : kotlin.Int = 56 // kotlin.Int | 
            //val manufacturerName : kotlin.String = manufacturerName_example // kotlin.String | 
            //val name : kotlin.String = name_example // kotlin.String | 
            //val offset : kotlin.Int = 56 // kotlin.Int | The initial index from which to return the results.
            //val `operator` : kotlin.Int = 56 // kotlin.Int | 
            //val operatorId : kotlin.Int = 56 // kotlin.Int | 
            //val operatorName : kotlin.String = operatorName_example // kotlin.String | 
            //val ordering : kotlin.String = ordering_example // kotlin.String | Which field to use when ordering the results.
            //val programId : kotlin.Int = 56 // kotlin.Int | 
            //val search : kotlin.String = search_example // kotlin.String | A search term.
            //val result : PaginatedPayloadNormalList = apiInstance.payloadsList(limit, manufacturerId, manufacturerName, name, offset, `operator`, operatorId, operatorName, ordering, programId, search)
            //result shouldBe ("TODO")
        }

        // to test payloadsMiniList
        should("test payloadsMiniList") {
            // uncomment below to test payloadsMiniList
            //val limit : kotlin.Int = 56 // kotlin.Int | Number of results to return per page.
            //val manufacturerId : kotlin.Int = 56 // kotlin.Int | 
            //val manufacturerName : kotlin.String = manufacturerName_example // kotlin.String | 
            //val name : kotlin.String = name_example // kotlin.String | 
            //val offset : kotlin.Int = 56 // kotlin.Int | The initial index from which to return the results.
            //val `operator` : kotlin.Int = 56 // kotlin.Int | 
            //val operatorId : kotlin.Int = 56 // kotlin.Int | 
            //val operatorName : kotlin.String = operatorName_example // kotlin.String | 
            //val ordering : kotlin.String = ordering_example // kotlin.String | Which field to use when ordering the results.
            //val programId : kotlin.Int = 56 // kotlin.Int | 
            //val search : kotlin.String = search_example // kotlin.String | A search term.
            //val result : PaginatedPayloadMiniList = apiInstance.payloadsMiniList(limit, manufacturerId, manufacturerName, name, offset, `operator`, operatorId, operatorName, ordering, programId, search)
            //result shouldBe ("TODO")
        }

        // to test payloadsRetrieve
        should("test payloadsRetrieve") {
            // uncomment below to test payloadsRetrieve
            //val id : kotlin.Int = 56 // kotlin.Int | A unique integer value identifying this payload.
            //val result : PayloadDetailed = apiInstance.payloadsRetrieve(id)
            //result shouldBe ("TODO")
        }

    }
}
