/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.client.models

import me.calebjones.spacelaunchnow.api.client.models.CelestialBodyType
import me.calebjones.spacelaunchnow.api.client.models.Image
import me.calebjones.spacelaunchnow.api.client.models.LocationSerializerNoCelestialBody

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param responseMode 
 * @param id 
 * @param name 
 * @param type 
 * @param image 
 * @param locations 
 * @param diameter m
 * @param mass kg
 * @param gravity m/s^2
 * @param lengthOfDay 
 * @param atmosphere 
 * @param description 
 * @param wikiUrl 
 * @param totalAttemptedLaunches 
 * @param successfulLaunches 
 * @param failedLaunches 
 * @param totalAttemptedLandings 
 * @param successfulLandings 
 * @param failedLandings 
 */
@Serializable

data class CelestialBodyEndpointDetailed (

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "detailed",

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "type") @Required val type: CelestialBodyType,

    @SerialName(value = "image") @Required val image: Image,

    @SerialName(value = "locations") @Required val locations: kotlin.collections.List<LocationSerializerNoCelestialBody>,

    /* m */
    @SerialName(value = "diameter") val diameter: kotlin.Double? = null,

    /* kg */
    @SerialName(value = "mass") val mass: kotlin.Double? = null,

    /* m/s^2 */
    @SerialName(value = "gravity") val gravity: kotlin.Double? = null,

    @SerialName(value = "length_of_day") val lengthOfDay: kotlin.String? = null,

    @SerialName(value = "atmosphere") val atmosphere: kotlin.Boolean? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "wiki_url") val wikiUrl: kotlin.String? = null,

    @SerialName(value = "total_attempted_launches") val totalAttemptedLaunches: kotlin.Int? = null,

    @SerialName(value = "successful_launches") val successfulLaunches: kotlin.Int? = null,

    @SerialName(value = "failed_launches") val failedLaunches: kotlin.Int? = null,

    @SerialName(value = "total_attempted_landings") val totalAttemptedLandings: kotlin.Int? = null,

    @SerialName(value = "successful_landings") val successfulLandings: kotlin.Int? = null,

    @SerialName(value = "failed_landings") val failedLandings: kotlin.Int? = null

) {


}

