/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.client.models

import me.calebjones.spacelaunchnow.api.client.models.AstronautFlight
import me.calebjones.spacelaunchnow.api.client.models.MissionPatch
import me.calebjones.spacelaunchnow.api.client.models.SpaceStationDetailed
import me.calebjones.spacelaunchnow.api.client.models.SpacewalkList

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param url 
 * @param name 
 * @param start 
 * @param responseMode 
 * @param spacestation 
 * @param missionPatches 
 * @param spacewalks 
 * @param crew 
 * @param end 
 */
@Serializable

data class ExpeditionDetailed (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "start") @Required val start: kotlinx.datetime.Instant,

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "detailed",

    @SerialName(value = "spacestation") @Required val spacestation: SpaceStationDetailed,

    @SerialName(value = "mission_patches") @Required val missionPatches: kotlin.collections.List<MissionPatch>,

    @SerialName(value = "spacewalks") @Required val spacewalks: kotlin.collections.List<SpacewalkList>,

    @SerialName(value = "crew") @Required val crew: kotlin.collections.List<AstronautFlight>,

    @SerialName(value = "end") val end: kotlinx.datetime.Instant? = null

) {


}

