/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.client.models

import me.calebjones.spacelaunchnow.api.client.models.AgencyDetailed
import me.calebjones.spacelaunchnow.api.client.models.Image
import me.calebjones.spacelaunchnow.api.client.models.InfoURL
import me.calebjones.spacelaunchnow.api.client.models.LaunchStatus
import me.calebjones.spacelaunchnow.api.client.models.Mission
import me.calebjones.spacelaunchnow.api.client.models.MissionPatch
import me.calebjones.spacelaunchnow.api.client.models.NetPrecision
import me.calebjones.spacelaunchnow.api.client.models.Pad
import me.calebjones.spacelaunchnow.api.client.models.ProgramNormal
import me.calebjones.spacelaunchnow.api.client.models.RocketDetailed
import me.calebjones.spacelaunchnow.api.client.models.TimelineEvent
import me.calebjones.spacelaunchnow.api.client.models.Update
import me.calebjones.spacelaunchnow.api.client.models.VidURL

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param url 
 * @param responseMode 
 * @param slug 
 * @param status 
 * @param netPrecision 
 * @param image 
 * @param infographic 
 * @param launchServiceProvider 
 * @param rocket 
 * @param mission 
 * @param pad 
 * @param program 
 * @param updates 
 * @param infoUrls 
 * @param vidUrls 
 * @param timeline 
 * @param padTurnaround 
 * @param missionPatches 
 * @param name 
 * @param launchDesignator 
 * @param lastUpdated 
 * @param net 
 * @param windowEnd 
 * @param windowStart 
 * @param probability 
 * @param weatherConcerns 
 * @param failreason 
 * @param hashtag 
 * @param webcastLive 
 * @param orbitalLaunchAttemptCount 
 * @param locationLaunchAttemptCount 
 * @param padLaunchAttemptCount 
 * @param agencyLaunchAttemptCount 
 * @param orbitalLaunchAttemptCountYear 
 * @param locationLaunchAttemptCountYear 
 * @param padLaunchAttemptCountYear 
 * @param agencyLaunchAttemptCountYear 
 * @param flightclubUrl 
 */
@Serializable
@SerialName("detailed")
data class LaunchDetailed (

    @SerialName(value = "id") @Required override val id: kotlin.String,

    @SerialName(value = "url") @Required override val url: kotlin.String,

    @SerialName(value = "slug") @Required val slug: kotlin.String,

    @SerialName(value = "status") @Required val status: LaunchStatus?,

    @SerialName(value = "net_precision") @Required val netPrecision: NetPrecision?,

    @SerialName(value = "image") @Required override val image: Image?,

    @SerialName(value = "infographic") @Required val infographic: kotlin.String?,

    @SerialName(value = "launch_service_provider") @Required val launchServiceProvider: AgencyDetailed?,

    @SerialName(value = "rocket") @Required val rocket: RocketDetailed?,

    @SerialName(value = "mission") @Required val mission: Mission?,

    @SerialName(value = "pad") @Required val pad: Pad?,

    @SerialName(value = "program") @Required val program: kotlin.collections.List<ProgramNormal>?,

    @SerialName(value = "updates") @Required val updates: kotlin.collections.List<Update>,

    @SerialName(value = "info_urls") @Required val infoUrls: kotlin.collections.List<InfoURL>,

    @SerialName(value = "vid_urls") @Required val vidUrls: kotlin.collections.List<VidURL>,

    @SerialName(value = "timeline") @Required val timeline: kotlin.collections.List<TimelineEvent>,

    @SerialName(value = "pad_turnaround") @Required val padTurnaround: kotlin.String,

    @SerialName(value = "mission_patches") @Required val missionPatches: kotlin.collections.List<MissionPatch>,

    @SerialName(value = "name") override val name: kotlin.String,

    @SerialName(value = "launch_designator") val launchDesignator: kotlin.String? = null,

    @SerialName(value = "last_updated") val lastUpdated: kotlinx.datetime.Instant? = null,

    @SerialName(value = "net") val net: kotlinx.datetime.Instant? = null,

    @SerialName(value = "window_end") val windowEnd: kotlinx.datetime.Instant? = null,

    @SerialName(value = "window_start") val windowStart: kotlinx.datetime.Instant? = null,

    @SerialName(value = "probability") val probability: kotlin.Int? = null,

    @SerialName(value = "weather_concerns") val weatherConcerns: kotlin.String? = null,

    @SerialName(value = "failreason") val failreason: kotlin.String? = null,

    @SerialName(value = "hashtag") val hashtag: kotlin.String? = null,

    @SerialName(value = "webcast_live") val webcastLive: kotlin.Boolean? = null,

    @SerialName(value = "orbital_launch_attempt_count") val orbitalLaunchAttemptCount: kotlin.Int? = null,

    @SerialName(value = "location_launch_attempt_count") val locationLaunchAttemptCount: kotlin.Int? = null,

    @SerialName(value = "pad_launch_attempt_count") val padLaunchAttemptCount: kotlin.Int? = null,

    @SerialName(value = "agency_launch_attempt_count") val agencyLaunchAttemptCount: kotlin.Int? = null,

    @SerialName(value = "orbital_launch_attempt_count_year") val orbitalLaunchAttemptCountYear: kotlin.Int? = null,

    @SerialName(value = "location_launch_attempt_count_year") val locationLaunchAttemptCountYear: kotlin.Int? = null,

    @SerialName(value = "pad_launch_attempt_count_year") val padLaunchAttemptCountYear: kotlin.Int? = null,

    @SerialName(value = "agency_launch_attempt_count_year") val agencyLaunchAttemptCountYear: kotlin.Int? = null,

    @SerialName(value = "flightclub_url") val flightclubUrl: kotlin.String? = null

) : PolymorphicLaunchEndpoint()

