/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.client.models

import me.calebjones.spacelaunchnow.api.client.models.AgencyDetailed
import me.calebjones.spacelaunchnow.api.client.models.Image
import me.calebjones.spacelaunchnow.api.client.models.InfoURL
import me.calebjones.spacelaunchnow.api.client.models.Orbit
import me.calebjones.spacelaunchnow.api.client.models.VidURL

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param type 
 * @param image 
 * @param orbit 
 * @param agencies 
 * @param infoUrls 
 * @param vidUrls 
 * @param description 
 */
@Serializable

data class Mission (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "type") @Required val type: kotlin.String,

    @SerialName(value = "image") @Required val image: Image?,

    @SerialName(value = "orbit") @Required val orbit: Orbit,

    @SerialName(value = "agencies") @Required val agencies: kotlin.collections.List<AgencyDetailed>,

    @SerialName(value = "info_urls") @Required val infoUrls: kotlin.collections.List<InfoURL>,

    @SerialName(value = "vid_urls") @Required val vidUrls: kotlin.collections.List<VidURL>,

    @SerialName(value = "description") val description: kotlin.String? = null

) {


}

