/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.client.models

import me.calebjones.spacelaunchnow.api.client.models.AgencyNormal
import me.calebjones.spacelaunchnow.api.client.models.Image
import me.calebjones.spacelaunchnow.api.client.models.PayloadType
import me.calebjones.spacelaunchnow.api.client.models.ProgramMini

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param responseMode 
 * @param id 
 * @param type 
 * @param manufacturer 
 * @param `operator` 
 * @param image 
 * @param program 
 * @param name 
 * @param wikiLink 
 * @param infoLink 
 * @param cost 
 * @param mass 
 * @param description 
 */
@Serializable

data class PayloadNormal (

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "normal",

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "type") @Required val type: PayloadType,

    @SerialName(value = "manufacturer") @Required val manufacturer: AgencyNormal,

    @SerialName(value = "operator") @Required val `operator`: AgencyNormal,

    @SerialName(value = "image") @Required val image: Image?,

    @SerialName(value = "program") @Required val program: kotlin.collections.List<ProgramMini>,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "wiki_link") val wikiLink: kotlin.String? = null,

    @SerialName(value = "info_link") val infoLink: kotlin.String? = null,

    @SerialName(value = "cost") val cost: kotlin.Int? = null,

    @SerialName(value = "mass") val mass: kotlin.Double? = null,

    @SerialName(value = "description") val description: kotlin.String? = null

) {


}

