/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.client.models

import me.calebjones.spacelaunchnow.api.client.models.AgencyMini
import me.calebjones.spacelaunchnow.api.client.models.Image
import me.calebjones.spacelaunchnow.api.client.models.PayloadType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param responseMode 
 * @param id 
 * @param type 
 * @param manufacturer 
 * @param `operator` 
 * @param image 
 * @param name 
 */
@Serializable

data class PayloadMini (

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "list",

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "type") @Required val type: PayloadType,

    @SerialName(value = "manufacturer") @Required val manufacturer: AgencyMini,

    @SerialName(value = "operator") @Required val `operator`: AgencyMini,

    @SerialName(value = "image") @Required val image: Image?,

    @SerialName(value = "name") val name: kotlin.String? = null

) {


}

