/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.client.models

import me.calebjones.spacelaunchnow.api.client.models.FirstStageDetailedSerializerNoLanding
import me.calebjones.spacelaunchnow.api.client.models.LandingEndpointDetailed
import me.calebjones.spacelaunchnow.api.client.models.LandingEndpointList
import me.calebjones.spacelaunchnow.api.client.models.LandingEndpointNormal
import me.calebjones.spacelaunchnow.api.client.models.LandingLocation
import me.calebjones.spacelaunchnow.api.client.models.LandingType
import me.calebjones.spacelaunchnow.api.client.models.PayloadFlightDetailedSerializerNoLanding
import me.calebjones.spacelaunchnow.api.client.models.SpacecraftFlightDetailedSerializerNoLanding

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param url 
 * @param landingLocation 
 * @param type 
 * @param responseMode 
 * @param firststage 
 * @param spacecraftflight 
 * @param payloadflight 
 * @param attempt 
 * @param success 
 * @param description 
 * @param downrangeDistance 
 */


interface PolymorphicLandingEndpoint {

    @SerialName(value = "id") @Required val id: kotlin.Int
    @SerialName(value = "url") @Required val url: kotlin.String
    @SerialName(value = "landing_location") @Required val landingLocation: LandingLocation
    @SerialName(value = "type") @Required val type: LandingType
    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String
    @SerialName(value = "firststage") @Required val firststage: FirstStageDetailedSerializerNoLanding
    @SerialName(value = "spacecraftflight") @Required val spacecraftflight: SpacecraftFlightDetailedSerializerNoLanding
    @SerialName(value = "payloadflight") @Required val payloadflight: PayloadFlightDetailedSerializerNoLanding
    @SerialName(value = "attempt") val attempt: kotlin.Boolean?
    @SerialName(value = "success") val success: kotlin.Boolean?
    @SerialName(value = "description") val description: kotlin.String?
    @SerialName(value = "downrange_distance") val downrangeDistance: kotlin.Double?

}

