/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.client.models

import me.calebjones.spacelaunchnow.api.client.models.AgencyDetailed
import me.calebjones.spacelaunchnow.api.client.models.Image
import me.calebjones.spacelaunchnow.api.client.models.LauncherConfigDetailed
import me.calebjones.spacelaunchnow.api.client.models.LauncherConfigFamilyDetailed
import me.calebjones.spacelaunchnow.api.client.models.LauncherConfigList
import me.calebjones.spacelaunchnow.api.client.models.LauncherConfigNormal
import me.calebjones.spacelaunchnow.api.client.models.ProgramNormal

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param responseMode 
 * @param id 
 * @param url 
 * @param name 
 * @param families 
 * @param manufacturer 
 * @param program 
 * @param image 
 * @param fastestTurnaround 
 * @param fullName 
 * @param variant 
 * @param active 
 * @param isPlaceholder 
 * @param reusable 
 * @param infoUrl 
 * @param wikiUrl 
 * @param description 
 * @param alias 
 * @param minStage 
 * @param maxStage 
 * @param length 
 * @param diameter 
 * @param maidenFlight 
 * @param launchCost 
 * @param launchMass 
 * @param leoCapacity 
 * @param gtoCapacity 
 * @param geoCapacity 
 * @param ssoCapacity 
 * @param toThrust 
 * @param apogee 
 * @param totalLaunchCount 
 * @param consecutiveSuccessfulLaunches 
 * @param successfulLaunches 
 * @param failedLaunches 
 * @param pendingLaunches 
 * @param attemptedLandings 
 * @param successfulLandings 
 * @param failedLandings 
 * @param consecutiveSuccessfulLandings 
 */


interface PolymorphicLauncherConfigEndpoint {

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String
    @SerialName(value = "id") @Required val id: kotlin.Int
    @SerialName(value = "url") @Required val url: kotlin.String
    @SerialName(value = "name") @Required val name: kotlin.String
    @SerialName(value = "families") @Required val families: kotlin.collections.List<LauncherConfigFamilyDetailed>?
    @SerialName(value = "manufacturer") @Required val manufacturer: AgencyDetailed?
    @SerialName(value = "program") @Required val program: kotlin.collections.List<ProgramNormal>
    @SerialName(value = "image") @Required val image: Image?
    @SerialName(value = "fastest_turnaround") @Required val fastestTurnaround: kotlin.String?
    @SerialName(value = "full_name") val fullName: kotlin.String?
    @SerialName(value = "variant") val variant: kotlin.String?
    @SerialName(value = "active") val active: kotlin.Boolean?
    @SerialName(value = "is_placeholder") val isPlaceholder: kotlin.Boolean?
    @SerialName(value = "reusable") val reusable: kotlin.Boolean?
    @SerialName(value = "info_url") val infoUrl: kotlin.String?
    @SerialName(value = "wiki_url") val wikiUrl: kotlin.String?
    @SerialName(value = "description") val description: kotlin.String?
    @SerialName(value = "alias") val alias: kotlin.String?
    @SerialName(value = "min_stage") val minStage: kotlin.Int?
    @SerialName(value = "max_stage") val maxStage: kotlin.Int?
    @SerialName(value = "length") val length: kotlin.Double?
    @SerialName(value = "diameter") val diameter: kotlin.Double?
    @SerialName(value = "maiden_flight") val maidenFlight: kotlinx.datetime.LocalDate?
    @SerialName(value = "launch_cost") val launchCost: kotlin.Int?
    @SerialName(value = "launch_mass") val launchMass: kotlin.Double?
    @SerialName(value = "leo_capacity") val leoCapacity: kotlin.Double?
    @SerialName(value = "gto_capacity") val gtoCapacity: kotlin.Double?
    @SerialName(value = "geo_capacity") val geoCapacity: kotlin.Double?
    @SerialName(value = "sso_capacity") val ssoCapacity: kotlin.Double?
    @SerialName(value = "to_thrust") val toThrust: kotlin.Double?
    @SerialName(value = "apogee") val apogee: kotlin.Double?
    @SerialName(value = "total_launch_count") val totalLaunchCount: kotlin.Int?
    @SerialName(value = "consecutive_successful_launches") val consecutiveSuccessfulLaunches: kotlin.Int?
    @SerialName(value = "successful_launches") val successfulLaunches: kotlin.Int?
    @SerialName(value = "failed_launches") val failedLaunches: kotlin.Int?
    @SerialName(value = "pending_launches") val pendingLaunches: kotlin.Int?
    @SerialName(value = "attempted_landings") val attemptedLandings: kotlin.Int?
    @SerialName(value = "successful_landings") val successfulLandings: kotlin.Int?
    @SerialName(value = "failed_landings") val failedLandings: kotlin.Int?
    @SerialName(value = "consecutive_successful_landings") val consecutiveSuccessfulLandings: kotlin.Int?

}

