/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.client.models

import me.calebjones.spacelaunchnow.api.client.models.Image
import me.calebjones.spacelaunchnow.api.client.models.LauncherConfigList
import me.calebjones.spacelaunchnow.api.client.models.LauncherDetailed
import me.calebjones.spacelaunchnow.api.client.models.LauncherMini
import me.calebjones.spacelaunchnow.api.client.models.LauncherNormal
import me.calebjones.spacelaunchnow.api.client.models.LauncherStatus

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param responseMode 
 * @param id 
 * @param url 
 * @param status 
 * @param image 
 * @param fastestTurnaround 
 * @param launcherConfig 
 * @param flightProven 
 * @param serialNumber 
 * @param isPlaceholder 
 * @param details 
 * @param successfulLandings 
 * @param attemptedLandings 
 * @param flights 
 * @param lastLaunchDate 
 * @param firstLaunchDate 
 */


interface PolymorphicLauncherEndpoint {

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String
    @SerialName(value = "id") @Required val id: kotlin.Int
    @SerialName(value = "url") @Required val url: kotlin.String
    @SerialName(value = "status") @Required val status: LauncherStatus?
    @SerialName(value = "image") @Required val image: Image?
    @SerialName(value = "fastest_turnaround") @Required val fastestTurnaround: kotlin.String?
    @SerialName(value = "launcher_config") @Required val launcherConfig: LauncherConfigList?
    @SerialName(value = "flight_proven") val flightProven: kotlin.Boolean?
    @SerialName(value = "serial_number") val serialNumber: kotlin.String?
    @SerialName(value = "is_placeholder") val isPlaceholder: kotlin.Boolean?
    @SerialName(value = "details") val details: kotlin.String?
    @SerialName(value = "successful_landings") val successfulLandings: kotlin.Int?
    @SerialName(value = "attempted_landings") val attemptedLandings: kotlin.Int?
    @SerialName(value = "flights") val flights: kotlin.Int?
    @SerialName(value = "last_launch_date") val lastLaunchDate: kotlinx.datetime.Instant?
    @SerialName(value = "first_launch_date") val firstLaunchDate: kotlinx.datetime.Instant?

}

