/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.client.models

import me.calebjones.spacelaunchnow.api.client.models.AgencyDetailed
import me.calebjones.spacelaunchnow.api.client.models.LauncherConfigFamilyDetailed
import me.calebjones.spacelaunchnow.api.client.models.LauncherConfigFamilyMini
import me.calebjones.spacelaunchnow.api.client.models.LauncherConfigFamilyNormal

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param responseMode 
 * @param id 
 * @param name 
 * @param manufacturer 
 * @param parent 
 * @param description 
 * @param active 
 * @param maidenFlight 
 * @param totalLaunchCount 
 * @param consecutiveSuccessfulLaunches 
 * @param successfulLaunches 
 * @param failedLaunches 
 * @param pendingLaunches 
 * @param attemptedLandings 
 * @param successfulLandings 
 * @param failedLandings 
 * @param consecutiveSuccessfulLandings 
 */


interface PolymorphicLauncherConfigFamilyEndpoint {

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String
    @SerialName(value = "id") @Required val id: kotlin.Int
    @SerialName(value = "name") @Required val name: kotlin.String
    @SerialName(value = "manufacturer") @Required val manufacturer: kotlin.collections.List<AgencyDetailed>?
    @SerialName(value = "parent") @Required val parent: LauncherConfigFamilyNormal?
    @SerialName(value = "description") val description: kotlin.String?
    @SerialName(value = "active") val active: kotlin.Boolean?
    @SerialName(value = "maiden_flight") val maidenFlight: kotlinx.datetime.LocalDate?
    @SerialName(value = "total_launch_count") val totalLaunchCount: kotlin.Int?
    @SerialName(value = "consecutive_successful_launches") val consecutiveSuccessfulLaunches: kotlin.Int?
    @SerialName(value = "successful_launches") val successfulLaunches: kotlin.Int?
    @SerialName(value = "failed_launches") val failedLaunches: kotlin.Int?
    @SerialName(value = "pending_launches") val pendingLaunches: kotlin.Int?
    @SerialName(value = "attempted_landings") val attemptedLandings: kotlin.Int?
    @SerialName(value = "successful_landings") val successfulLandings: kotlin.Int?
    @SerialName(value = "failed_landings") val failedLandings: kotlin.Int?
    @SerialName(value = "consecutive_successful_landings") val consecutiveSuccessfulLandings: kotlin.Int?

}

