/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.client.models

import me.calebjones.spacelaunchnow.api.client.models.AstronautFlight
import me.calebjones.spacelaunchnow.api.client.models.DockingEventForChaserNormal
import me.calebjones.spacelaunchnow.api.client.models.Landing
import me.calebjones.spacelaunchnow.api.client.models.LaunchNormal
import me.calebjones.spacelaunchnow.api.client.models.SpacecraftDetailed

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param url 
 * @param spacecraft 
 * @param launch 
 * @param landing 
 * @param duration 
 * @param turnAroundTime 
 * @param responseMode 
 * @param launchCrew 
 * @param onboardCrew 
 * @param landingCrew 
 * @param dockingEvents 
 * @param destination 
 * @param missionEnd 
 */
@Serializable

data class SpacecraftFlightDetailed (

    @SerialName(value = "id") @Required val id: kotlin.Int,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "spacecraft") @Required val spacecraft: SpacecraftDetailed,

    @SerialName(value = "launch") @Required val launch: LaunchNormal,

    @SerialName(value = "landing") @Required val landing: Landing,

    @SerialName(value = "duration") @Required val duration: kotlin.String,

    @SerialName(value = "turn_around_time") @Required val turnAroundTime: kotlin.String,

    @SerialName(value = "response_mode") @Required val responseMode: kotlin.String = "detailed",

    @SerialName(value = "launch_crew") @Required val launchCrew: kotlin.collections.List<AstronautFlight>,

    @SerialName(value = "onboard_crew") @Required val onboardCrew: kotlin.collections.List<AstronautFlight>,

    @SerialName(value = "landing_crew") @Required val landingCrew: kotlin.collections.List<AstronautFlight>,

    @SerialName(value = "docking_events") @Required val dockingEvents: kotlin.collections.List<DockingEventForChaserNormal>,

    @SerialName(value = "destination") val destination: kotlin.String? = null,

    @SerialName(value = "mission_end") val missionEnd: kotlinx.datetime.Instant? = null

) {


}

