/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.calebjones.spacelaunchnow.api.snapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import me.calebjones.spacelaunchnow.api.snapi.models.Article
import me.calebjones.spacelaunchnow.api.snapi.models.Author
import me.calebjones.spacelaunchnow.api.snapi.models.Event
import me.calebjones.spacelaunchnow.api.snapi.models.Launch

class ArticleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Article
        //val modelInstance = Article()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `authors`
        should("test authors") {
            // uncomment below to test the property
            //modelInstance.authors shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `imageUrl`
        should("test imageUrl") {
            // uncomment below to test the property
            //modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `newsSite`
        should("test newsSite") {
            // uncomment below to test the property
            //modelInstance.newsSite shouldBe ("TODO")
        }

        // to test the property `summary`
        should("test summary") {
            // uncomment below to test the property
            //modelInstance.summary shouldBe ("TODO")
        }

        // to test the property `publishedAt`
        should("test publishedAt") {
            // uncomment below to test the property
            //modelInstance.publishedAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `launches`
        should("test launches") {
            // uncomment below to test the property
            //modelInstance.launches shouldBe ("TODO")
        }

        // to test the property `events`
        should("test events") {
            // uncomment below to test the property
            //modelInstance.events shouldBe ("TODO")
        }

        // to test the property `featured`
        should("test featured") {
            // uncomment below to test the property
            //modelInstance.featured shouldBe ("TODO")
        }

    }
}
